import type { Brand, BrandAstrology, BrandCategory, BrandNumerology } from '@/types/cosmic';

type ZodSign = "aries" | "taurus" | "gemini" | "cancer" | "leo" | "virgo" | "libra" | "scorpio" | "sagittarius" | "capricorn" | "aquarius" | "pisces";
type PName = "sun" | "moon" | "mercury" | "venus" | "mars" | "jupiter" | "saturn" | "uranus" | "neptune" | "pluto";
type ZodEl = "fire" | "earth" | "air" | "water";

interface RawBrand {
  id: string; name: string; slug: string; cat: BrandCategory; desc: string; tagline: string;
  logo: string; year: number; founder: string; bn: number; z: ZodSign;
  kw: string[]; lc: string[]; ln: number[]; energy: string;
}

function transformBrand(raw: RawBrand): Brand {
  const zodToAstrology = (sign: ZodSign): BrandAstrology => {
    const ruling: Record<ZodSign, PName> = {
      aries: "mars", taurus: "venus", gemini: "mercury", cancer: "moon",
      leo: "sun", virgo: "mercury", libra: "venus", scorpio: "pluto",
      sagittarius: "jupiter", capricorn: "saturn", aquarius: "uranus", pisces: "neptune",
    };
    const elem: Record<ZodSign, ZodEl> = {
      aries: "fire", taurus: "earth", gemini: "air", cancer: "water",
      leo: "fire", virgo: "earth", libra: "air", scorpio: "water",
      sagittarius: "fire", capricorn: "earth", aquarius: "air", pisces: "water",
    };
    const compatible: Record<ZodSign, ZodSign[]> = {
      aries: ["leo", "sagittarius", "gemini"], taurus: ["virgo", "capricorn", "cancer"],
      gemini: ["libra", "aquarius", "aries"], cancer: ["scorpio", "pisces", "taurus"],
      leo: ["aries", "sagittarius", "libra"], virgo: ["taurus", "capricorn", "cancer"],
      libra: ["gemini", "aquarius", "leo"], scorpio: ["cancer", "pisces", "virgo"],
      sagittarius: ["aries", "leo", "aquarius"], capricorn: ["taurus", "virgo", "scorpio"],
      aquarius: ["gemini", "libra", "sagittarius"], pisces: ["cancer", "scorpio", "virgo"],
    };
    return {
      zodiacSign: sign,
      rulingPlanet: ruling[sign],
      element: elem[sign],
      compatibleSigns: compatible[sign],
    };
  };

  const numerology: BrandNumerology = {
    brandNumber: raw.bn,
    expression: "—",
    strengths: ["Innovation", "Growth"],
    challenges: ["Balance", "Integration"],
  };

  return {
    id: raw.id,
    name: raw.name,
    slug: raw.slug,
    category: raw.cat,
    description: raw.desc,
    tagline: raw.tagline,
    logo: raw.logo,
    foundedYear: raw.year,
    founder: raw.founder,
    numerology,
    astrology: zodToAstrology(raw.z),
    keywords: raw.kw,
    luckyColors: raw.lc,
    luckyNumbers: raw.ln,
    energy: raw.energy,
  };
}

const RAW: RawBrand[] = [
  // === TECHNOLOGY ===
  { id: "apple", name: "Apple", slug: "apple", cat: "technology", desc: "Pioneering technology company known for innovative hardware, software, and services. Creator of iPhone, Mac, iPad, and a seamless ecosystem of products.", tagline: "Think Different", logo: "🍎", year: 1976, founder: "Steve Jobs, Steve Wozniak", bn: 5, z: "aquarius", kw: ["innovation","design","simplicity","premium","ecosystem"], lc: ["#A2AAAD","#000000"], ln: [5,7,11,22], energy: "Revolutionary — challenges conventions and redefines industries" },
  { id: "samsung", name: "Samsung", slug: "samsung", cat: "technology", desc: "Global leader in electronics, semiconductors, and mobile technology. Known for Galaxy smartphones, displays, and home appliances.", tagline: "Do What You Can't", logo: "📱", year: 1938, founder: "Lee Byung-chul", bn: 22, z: "virgo", kw: ["innovation","quality","precision","scale","diversity"], lc: ["#1428A0","#000000"], ln: [22,4,7,8], energy: "Master Builder — turns visionary ideas into tangible reality at massive scale" },
  { id: "google", name: "Google", slug: "google", cat: "technology", desc: "Search and technology giant that organizes the world's information. Creator of Android, Chrome, YouTube, and countless AI-driven services.", tagline: "Don't Be Evil", logo: "🔍", year: 1998, founder: "Larry Page, Sergey Brin", bn: 7, z: "aquarius", kw: ["search","data","innovation","AI","information"], lc: ["#4285F4","#34A853","#FBBC05","#EA4335"], ln: [7,1,3,9], energy: "Seeker of Knowledge — on a mission to organize and democratize information" },
  { id: "microsoft", name: "Microsoft", slug: "microsoft", cat: "technology", desc: "Software powerhouse behind Windows, Office, Azure, and Xbox. Leading enterprise cloud computing and AI innovation.", tagline: "Be What's Next", logo: "🪟", year: 1975, founder: "Bill Gates, Paul Allen", bn: 1, z: "capricorn", kw: ["software","enterprise","cloud","productivity","platform"], lc: ["#00A4EF","#F25022","#7FBA00","#FFB900"], ln: [1,8,9,11], energy: "The Leader — builds the foundational tools that power modern business" },
  { id: "meta", name: "Meta", slug: "meta", cat: "technology", desc: "Social technology conglomerate connecting billions through Facebook, Instagram, WhatsApp, and the metaverse.", tagline: "Bringing the World Closer", logo: "🌐", year: 2004, founder: "Mark Zuckerberg", bn: 3, z: "gemini", kw: ["social","connection","communication","metaverse","community"], lc: ["#1877F2","#000000"], ln: [3,5,7,9], energy: "The Communicator — networks humanity on a global scale" },
  { id: "amazon", name: "Amazon", slug: "amazon", cat: "technology", desc: "E-commerce and cloud computing behemoth. From online retail to AWS, Alexa, and Prime, Amazon touches every aspect of modern life.", tagline: "Work Hard. Have Fun. Make History.", logo: "📦", year: 1994, founder: "Jeff Bezos", bn: 7, z: "sagittarius", kw: ["ecommerce","cloud","logistics","scale","customer-obsession"], lc: ["#FF9900","#131921"], ln: [7,1,3,9], energy: "The Explorer — ventures into uncharted markets with relentless ambition" },
  { id: "netflix", name: "Netflix", slug: "netflix", cat: "entertainment", desc: "World's leading streaming entertainment service with award-winning TV shows, movies, and documentaries across every genre.", tagline: "See What's Next", logo: "🎬", year: 1997, founder: "Reed Hastings, Marc Randolph", bn: 9, z: "pisces", kw: ["streaming","entertainment","content","original","binge"], lc: ["#E50914","#221F1F"], ln: [9,3,5,7], energy: "The Visionary — transformed how the world consumes stories" },
  { id: "spotify", name: "Spotify", slug: "spotify", cat: "entertainment", desc: "Digital music streaming service giving access to millions of songs, podcasts, and audio content from creators worldwide.", tagline: "Music for Everyone", logo: "🎵", year: 2006, founder: "Daniel Ek, Martin Lorentzon", bn: 2, z: "libra", kw: ["music","streaming","audio","playlist","discovery"], lc: ["#1DB954","#191414"], ln: [2,6,8,9], energy: "The Harmonizer — orchestrates the soundtrack of people's lives" },
  { id: "tesla-motors", name: "Tesla", slug: "tesla", cat: "automotive", desc: "Electric vehicle and clean energy company accelerating the world's transition to sustainable energy.", tagline: "Accelerate the World's Transition to Sustainable Energy", logo: "⚡", year: 2003, founder: "Martin Eberhard, Marc Tarpenning, Elon Musk", bn: 3, z: "aquarius", kw: ["EV","innovation","sustainability","autonomous","energy"], lc: ["#E82127","#000000"], ln: [3,5,7,9], energy: "The Revolutionary — disrupts entire industries with visionary technology" },
  // === AUTOMOTIVE ===
  { id: "toyota", name: "Toyota", slug: "toyota", cat: "automotive", desc: "World's largest automaker, renowned for reliability, innovation in hybrid technology, and the Toyota Production System.", tagline: "Let's Go Places", logo: "🚗", year: 1937, founder: "Kiichiro Toyoda", bn: 6, z: "taurus", kw: ["reliability","quality","sustainability","hybrid","durability"], lc: ["#FF0000","#000000"], ln: [6,4,8,9], energy: "The Nurturer — builds lasting value through consistent quality and care" },
  { id: "mercedes", name: "Mercedes-Benz", slug: "mercedes-benz", cat: "automotive", desc: "Prestigious German luxury automaker known for engineering excellence, safety innovation, and timeless design.", tagline: "The Best or Nothing", logo: "⭐", year: 1926, founder: "Karl Benz, Gottlieb Daimler", bn: 2, z: "capricorn", kw: ["luxury","engineering","prestige","safety","performance"], lc: ["#00A3E0","#000000"], ln: [2,4,6,8], energy: "The Architect — builds with precision, discipline, and uncompromising standards" },
  { id: "bmw", name: "BMW", slug: "bmw", cat: "automotive", desc: "Bavarian luxury vehicle manufacturer celebrated for driving dynamics, premium engineering, and the ultimate driving experience.", tagline: "The Ultimate Driving Machine", logo: "🚙", year: 1916, founder: "Franz Josef Popp", bn: 11, z: "leo", kw: ["performance","luxury","engineering","driving","prestige"], lc: ["#0066B1","#000000"], ln: [11,1,3,5], energy: "The Master — commands attention with power, presence, and performance" },
  { id: "audi", name: "Audi", slug: "audi", cat: "automotive", desc: "German luxury automaker known for sophisticated design, quattro all-wheel drive, and advanced automotive technology.", tagline: "Vorsprung Durch Technik", logo: "🔗", year: 1909, founder: "August Horch", bn: 8, z: "libra", kw: ["design","technology","luxury","sophistication","innovation"], lc: ["#000000","#FFFFFF"], ln: [8,2,4,6], energy: "The Executive — balances power with elegance and precision" },
  { id: "porsche", name: "Porsche", slug: "porsche", cat: "automotive", desc: "Iconic German sports car manufacturer famous for the 911 and its legacy of racing excellence and engineering artistry.", tagline: "There Is No Substitute", logo: "🏎️", year: 1931, founder: "Ferdinand Porsche", bn: 3, z: "aries", kw: ["speed","performance","legacy","engineering","racing"], lc: ["#000000","#B12B2E"], ln: [3,5,9,11], energy: "The Pioneer — leads with passion, speed, and fearless innovation" },
  { id: "ferrari", name: "Ferrari", slug: "ferrari", cat: "automotive", desc: "Legendary Italian luxury sports car manufacturer and racing team, synonymous with passion, speed, and automotive artistry.", tagline: "We Are the Competition", logo: "🐴", year: 1939, founder: "Enzo Ferrari", bn: 3, z: "leo", kw: ["passion","speed","luxury","racing","exclusivity"], lc: ["#FF2800","#FFD700"], ln: [3,1,5,8], energy: "The Performer — commands the stage with passion and fiery brilliance" },
  { id: "lamborghini", name: "Lamborghini", slug: "lamborghini", cat: "automotive", desc: "Italian supercar manufacturer known for bold, aggressive design and breathtaking performance. A symbol of audacious luxury.", tagline: "Feel the Impossible", logo: "🐂", year: 1963, founder: "Ferruccio Lamborghini", bn: 9, z: "aries", kw: ["extreme","power","luxury","design","performance"], lc: ["#FFD700","#000000"], ln: [9,1,3,5], energy: "The Warrior — charges forward with unstoppable force and fearless ambition" },
  { id: "ford", name: "Ford", slug: "ford", cat: "automotive", desc: "American automotive icon that revolutionized manufacturing with the assembly line and built the legendary Mustang.", tagline: "Built Ford Tough", logo: "🚙", year: 1903, founder: "Henry Ford", bn: 7, z: "taurus", kw: ["toughness","american","innovation","manufacturing","heritage"], lc: ["#003478","#000000"], ln: [7,1,3,6], energy: "The Builder — constructs enduring value through hard work and innovation" },
  { id: "honda", name: "Honda", slug: "honda", cat: "automotive", desc: "Japanese manufacturer of automobiles, motorcycles, and power equipment. Known for engineering efficiency and reliability.", tagline: "The Power of Dreams", logo: "🏍️", year: 1948, founder: "Soichiro Honda", bn: 6, z: "cancer", kw: ["reliability","efficiency","innovation","engineering","quality"], lc: ["#FF0000","#000000"], ln: [6,3,5,8], energy: "The Caretaker — nurtures innovation with precision and heart" },
  { id: "nissan", name: "Nissan", slug: "nissan", cat: "automotive", desc: "Japanese automaker known for innovative electric vehicles (Leaf), performance cars (GT-R), and accessible technology.", tagline: "Innovation That Excites", logo: "🔰", year: 1933, founder: "Yoshisuke Aikawa", bn: 22, z: "gemini", kw: ["innovation","electric","performance","technology","accessibility"], lc: ["#C3002F","#000000"], ln: [22,5,7,9], energy: "The Innovator — bridges cutting-edge technology with everyday life" },
  { id: "hyundai", name: "Hyundai", slug: "hyundai", cat: "automotive", desc: "South Korean automaker that has rapidly grown into a global leader with bold design, quality engineering, and EV leadership.", tagline: "New Thinking. New Possibilities.", logo: "🚘", year: 1967, founder: "Chung Ju-yung", bn: 1, z: "aries", kw: ["growth","innovation","design","quality","value"], lc: ["#002C5F","#FFFFFF"], ln: [1,3,5,8], energy: "The Achiever — transforms challenges into opportunities with relentless drive" },
  { id: "jaguar", name: "Jaguar", slug: "jaguar", cat: "automotive", desc: "British luxury vehicle manufacturer producing elegant, high-performance cars with distinctive design DNA.", tagline: "The Art of Performance", logo: "🐆", year: 1922, founder: "William Lyons", bn: 22, z: "virgo", kw: ["elegance","performance","craftsmanship","luxury","heritage"], lc: ["#006400","#000000"], ln: [22,4,6,8], energy: "The Artisan — perfects every detail with meticulous craftsmanship" },
  { id: "volvo", name: "Volvo", slug: "volvo", cat: "automotive", desc: "Swedish automaker renowned for safety leadership, Scandinavian design, and commitment to sustainability.", tagline: "For Life", logo: "🔒", year: 1927, founder: "Assar Gabrielsson, Gustaf Larson", bn: 5, z: "cancer", kw: ["safety","design","sustainability","family","protection"], lc: ["#003057","#FFFFFF"], ln: [5,2,4,6], energy: "The Guardian — protects what matters most with quiet strength" },
  { id: "volkswagen", name: "Volkswagen", slug: "volkswagen", cat: "automotive", desc: "German automaker known for the iconic Beetle and Golf, leading the automotive industry in volume and innovation.", tagline: "Das Auto", logo: "🚗", year: 1937, founder: "Ferdinand Porsche", bn: 3, z: "taurus", kw: ["innovation","reliability","german-engineering","heritage","accessibility"], lc: ["#001A4B","#FFFFFF"], ln: [3,4,6,8], energy: "The People's Car — brings quality engineering to the masses" },
  { id: "chevrolet", name: "Chevrolet", slug: "chevrolet", cat: "automotive", desc: "American automotive brand synonymous with performance, trucks, and the spirit of the open road.", tagline: "Find New Roads", logo: "🚙", year: 1911, founder: "Louis Chevrolet, William C. Durant", bn: 9, z: "aries", kw: ["american","performance","trucks","heritage","freedom"], lc: ["#C8102E","#000000"], ln: [9,1,3,7], energy: "The Free Spirit — embodies the freedom of the open road" },
  // === FASHION ===
  { id: "nike", name: "Nike", slug: "nike", cat: "fashion", desc: "Global athletic footwear and apparel leader inspiring athletes worldwide with innovative products and iconic branding.", tagline: "Just Do It", logo: "✅", year: 1964, founder: "Bill Bowerman, Phil Knight", bn: 3, z: "sagittarius", kw: ["athletics","performance","inspiration","innovation","motivation"], lc: ["#000000","#FFFFFF"], ln: [3,5,7,9], energy: "The Motivator — inspires action and pushes boundaries worldwide" },
  { id: "adidas", name: "Adidas", slug: "adidas", cat: "fashion", desc: "German sportswear giant blending athletic performance with streetwear culture. Three stripes are instantly iconic.", tagline: "Impossible Is Nothing", logo: "👟", year: 1949, founder: "Adi Dassler", bn: 2, z: "gemini", kw: ["sportswear","performance","streetwear","innovation","culture"], lc: ["#000000","#FFFFFF"], ln: [2,4,6,8], energy: "The Connector — bridges athletic excellence and cultural expression" },
  { id: "gucci", name: "Gucci", slug: "gucci", cat: "fashion", desc: "Italian luxury fashion house renowned for bold designs, craftsmanship, and iconic GG logo. A symbol of high-fashion opulence.", tagline: "The House of Gucci", logo: "👛", year: 1921, founder: "Guccio Gucci", bn: 7, z: "libra", kw: ["luxury","fashion","craftsmanship","heritage","bold"], lc: ["#2E8B57","#000000"], ln: [7,2,4,6], energy: "The Aesthete — defines elegance and beauty with bold sophistication" },
  { id: "prada", name: "Prada", slug: "prada", cat: "fashion", desc: "Italian luxury fashion house known for minimalist sophistication, innovative materials, and intellectual approach to design.", tagline: "Prada. The Experience.", logo: "👜", year: 1913, founder: "Mario Prada", bn: 22, z: "virgo", kw: ["minimalism","luxury","innovation","craftsmanship","intellectual"], lc: ["#000000","#FFFFFF"], ln: [22,4,6,8], energy: "The Purist — perfects minimalism with intellectual depth" },
  { id: "louis-vuitton", name: "Louis Vuitton", slug: "louis-vuitton", cat: "fashion", desc: "French fashion house and luxury goods company famous for LV monogram, travel trunks, and haute couture.", tagline: "The Art of Travel", logo: "🧳", year: 1854, founder: "Louis Vuitton", bn: 8, z: "taurus", kw: ["luxury","travel","craftsmanship","heritage","exclusivity"], lc: ["#C8A951","#8B6914"], ln: [8,2,4,6], energy: "The Emperor — commands luxury with timeless authority and refinement" },
  { id: "chanel", name: "Chanel", slug: "chanel", cat: "fashion", desc: "French fashion icon redefining women's style with timeless elegance, the little black dress, and Chanel No. 5 perfume.", tagline: "In Order to Be Irreplaceable, One Must Always Be Different", logo: "🌹", year: 1910, founder: "Coco Chanel", bn: 7, z: "libra", kw: ["elegance","femininity","timeless","luxury","revolution"], lc: ["#000000","#FFFFFF"], ln: [7,2,4,9], energy: "The Icon — redefined elegance and liberated women through fashion" },
  { id: "hermes", name: "Hermès", slug: "hermes", cat: "fashion", desc: "French luxury house specializing in leather, silk, and lifestyle goods. The Birkin bag symbolizes ultimate exclusivity.", tagline: "The Quality of Life", logo: "🧣", year: 1837, founder: "Thierry Hermès", bn: 5, z: "taurus", kw: ["craftsmanship","luxury","heritage","quality","exclusivity"], lc: ["#FF6600","#000000"], ln: [5,2,4,8], energy: "The Artisan — elevates craftsmanship to the highest form of art" },
  { id: "dior", name: "Dior", slug: "dior", cat: "fashion", desc: "French luxury fashion house founded by Christian Dior, known for haute couture, feminine silhouettes, and timeless glamour.", tagline: "The Elegance of Haute Couture", logo: "💃", year: 1946, founder: "Christian Dior", bn: 1, z: "libra", kw: ["elegance","femininity","luxury","couture","glamour"], lc: ["#000000","#FFFFFF"], ln: [1,3,5,7], energy: "The Visionary — creates beauty that transcends time" },
  { id: "versace", name: "Versace", slug: "versace", cat: "fashion", desc: "Italian luxury fashion house famous for bold prints, vibrant colors, and the iconic Medusa logo. Embodies glamour and audacity.", tagline: "Be Yourself. Don't Be Like Anyone Else.", logo: "👑", year: 1978, founder: "Gianni Versace", bn: 1, z: "leo", kw: ["bold","glamour","design","luxury","confidence"], lc: ["#000000","#FFD700"], ln: [1,3,5,9], energy: "The Star — radiates confidence, glamour, and regal presence" },
  { id: "burberry", name: "Burberry", slug: "burberry", cat: "fashion", desc: "British luxury fashion house known for iconic trench coats, check pattern, and heritage-inspired style.", tagline: "Art of the Trench", logo: "🧥", year: 1856, founder: "Thomas Burberry", bn: 1, z: "capricorn", kw: ["heritage","luxury","craftsmanship","british","timeless"], lc: ["#C1382D","#000000"], ln: [1,4,6,8], energy: "The Traditionalist — builds on heritage with disciplined excellence" },
  { id: "zara", name: "Zara", slug: "zara", cat: "fashion", desc: "Spanish fast-fashion retailer revolutionizing the industry with rapid design-to-shelf cycles and affordable chic.", tagline: "Love Your Look", logo: "👗", year: 1974, founder: "Amancio Ortega", bn: 1, z: "gemini", kw: ["fast-fashion","trends","speed","accessibility","style"], lc: ["#000000","#FFFFFF"], ln: [1,3,5,8], energy: "The Chameleon — adapts to trends with unmatched speed and agility" },
  { id: "hm", name: "H&M", slug: "hm", cat: "fashion", desc: "Swedish global fashion retailer offering trendy, sustainable clothing at accessible prices for everyone.", tagline: "Fashion and Quality at the Best Price", logo: "🧵", year: 1947, founder: "Erling Persson", bn: 3, z: "gemini", kw: ["fashion","affordable","sustainable","trends","retail"], lc: ["#FF0000","#000000"], ln: [3,5,7,9], energy: "The Democratizer — makes fashion accessible to all" },
  { id: "levi-strauss", name: "Levi Strauss", slug: "levi-strauss", cat: "fashion", desc: "American heritage brand that invented blue jeans, embodying rugged individualism and timeless style.", tagline: "Go Forth", logo: "👖", year: 1853, founder: "Levi Strauss", bn: 3, z: "sagittarius", kw: ["denim","heritage","american","individuality","freedom"], lc: ["#0000FF","#FFFFFF"], ln: [3,5,7,11], energy: "The Free Spirit — embodies adventure, freedom, and authentic character" },
  { id: "ralph-lauren", name: "Ralph Lauren", slug: "ralph-lauren", cat: "fashion", desc: "American fashion brand embodying aspirational lifestyle, preppy elegance, and timeless American style.", tagline: "The World of Ralph Lauren", logo: "👔", year: 1967, founder: "Ralph Lauren", bn: 9, z: "libra", kw: ["fashion","lifestyle","preppy","american","aspirational"], lc: ["#003366","#FFFFFF"], ln: [9,2,4,6], energy: "The Dreamer — curates an aspirational American lifestyle" },
  { id: "tommy-hilfiger", name: "Tommy Hilfiger", slug: "tommy-hilfiger", cat: "fashion", desc: "American fashion brand known for classic American cool, preppy style with a modern twist.", tagline: "American Classic. Modern Cool.", logo: "🇺🇸", year: 1985, founder: "Tommy Hilfiger", bn: 7, z: "gemini", kw: ["fashion","american","cool","preppy","youth"], lc: ["#003366","#FF0000","#FFFFFF"], ln: [7,2,3,5], energy: "The Classicist — reimagines American style with youthful energy" },
  // === FOOD & BEVERAGE ===
  { id: "cocacola", name: "Coca-Cola", slug: "cocacola", cat: "food-beverage", desc: "Iconic global beverage brand. The world's most recognized soft drink, symbolizing refreshment, happiness, and togetherness.", tagline: "Taste the Feeling", logo: "🥤", year: 1886, founder: "John Pemberton, Asa Griggs Candler", bn: 8, z: "cancer", kw: ["refreshment","happiness","heritage","global","nostalgia"], lc: ["#F40009","#000000"], ln: [8,2,3,6], energy: "The Nurturer — brings people together with timeless warmth and joy" },
  { id: "pepsi", name: "Pepsi", slug: "pepsi", cat: "food-beverage", desc: "Global carbonated soft drink brand and cultural icon, representing youthful energy and the choice of a new generation.", tagline: "For the Love of It", logo: "🥤", year: 1893, founder: "Caleb Bradham", bn: 2, z: "gemini", kw: ["refreshment","youth","energy","competition","culture"], lc: ["#004B93","#FF0000"], ln: [2,4,6,8], energy: "The Rival — thrives on competition and cultural relevance" },
  { id: "starbucks", name: "Starbucks", slug: "starbucks", cat: "food-beverage", desc: "Global coffeehouse chain that transformed coffee culture worldwide. Known for premium beverages and third-place experience.", tagline: "To Inspire and Nurture the Human Spirit", logo: "☕", year: 1971, founder: "Jerry Baldwin, Zev Siegl, Gordon Bowker", bn: 6, z: "cancer", kw: ["coffee","community","comfort","quality","experience"], lc: ["#006241","#D4AF37"], ln: [6,2,4,8], energy: "The Caregiver — creates a warm sanctuary for community and connection" },
  { id: "mcdonalds", name: "McDonald's", slug: "mcdonalds", cat: "food-beverage", desc: "World's largest fast-food restaurant chain, serving billions of customers with consistent quality, speed, and value.", tagline: "I'm Lovin' It", logo: "🍔", year: 1955, founder: "Ray Kroc, Richard McDonald, Maurice McDonald", bn: 4, z: "capricorn", kw: ["fast-food","consistency","global","family","efficiency"], lc: ["#FFC72C","#DA291C"], ln: [4,2,6,8], energy: "The Builder — built an empire on consistency, discipline, and scale" },
  { id: "nestle", name: "Nestlé", slug: "nestle", cat: "food-beverage", desc: "World's largest food and beverage company, offering nutrition, health, and wellness products globally.", tagline: "Good Food, Good Life", logo: "🍫", year: 1866, founder: "Henri Nestlé", bn: 3, z: "taurus", kw: ["nutrition","food","quality","global","heritage"], lc: ["#003D7A","#FFFFFF"], ln: [3,6,8,9], energy: "The Provider — nourishes generations with trusted quality" },
  { id: "kfc", name: "KFC", slug: "kfc", cat: "food-beverage", desc: "Global fast-food chain specializing in fried chicken. Colonel Sanders' secret recipe of 11 herbs and spices is legendary.", tagline: "Finger Lickin' Good", logo: "🍗", year: 1952, founder: "Harland Sanders", bn: 11, z: "leo", kw: ["fried-chicken","comfort-food","heritage","global","indulgence"], lc: ["#E4002B","#FFFFFF"], ln: [11,3,5,7], energy: "The Legend — built a global empire from a secret family recipe" },
  { id: "red-bull", name: "Red Bull", slug: "red-bull", cat: "food-beverage", desc: "Energy drink pioneer that created a new category. Known for extreme sports sponsorship and giving wings to dreams.", tagline: "Red Bull Gives You Wings", logo: "🪽", year: 1984, founder: "Dietrich Mateschitz", bn: 2, z: "aries", kw: ["energy","extreme","adventure","sponsorship","motivation"], lc: ["#004F9F","#C8102E"], ln: [2,1,3,5], energy: "The Daredevil — fuels adventure and pushes limits" },
  { id: "heineken", name: "Heineken", slug: "heineken", cat: "food-beverage", desc: "Dutch premium beer brand with global reach. Known for quality, green bottles, and the iconic red star.", tagline: "Open Your World", logo: "🍺", year: 1864, founder: "Gerard Heineken", bn: 8, z: "sagittarius", kw: ["beer","premium","global","social","heritage"], lc: ["#008200","#FF0000"], ln: [8,2,5,7], energy: "The Connector — brings people together across borders" },
  { id: "budweiser", name: "Budweiser", slug: "budweiser", cat: "food-beverage", desc: "American lager icon. The King of Beers represents tradition, patriotism, and American brewing heritage.", tagline: "The King of Beers", logo: "🍺", year: 1876, founder: "Adolphus Busch, Carl Conrad", bn: 7, z: "taurus", kw: ["beer","american","heritage","tradition","iconic"], lc: ["#FFCC00","#000000"], ln: [7,2,4,6], energy: "The Monarch — reigns with tradition, consistency, and pride" },
  { id: "subway", name: "Subway", slug: "subway", cat: "food-beverage", desc: "World's largest submarine sandwich chain, offering customizable fresh sandwiches made right in front of you.", tagline: "Eat Fresh", logo: "🥪", year: 1965, founder: "Fred DeLuca, Peter Buck", bn: 1, z: "gemini", kw: ["fast-food","sandwiches","fresh","customizable","global"], lc: ["#00843D","#FFCC00"], ln: [1,3,5,8], energy: "The Individualist — lets everyone create their own perfect meal" },
  { id: "domino", name: "Domino's", slug: "dominos", cat: "food-beverage", desc: "Global pizza delivery chain known for innovation in ordering technology, delivery speed, and consistent quality.", tagline: "You Got 30 Minutes", logo: "🍕", year: 1960, founder: "Tom Monaghan, James Monaghan", bn: 7, z: "aries", kw: ["pizza","delivery","technology","innovation","speed"], lc: ["#006491","#E31837"], ln: [7,1,3,5], energy: "The Disruptor — revolutionized food delivery through technology" },
  // === LUXURY ===
  { id: "lvmh", name: "LVMH", slug: "lvmh", cat: "luxury", desc: "World's largest luxury goods conglomerate, housing prestigious brands across fashion, wines, perfumes, and jewelry.", tagline: "The Spirit of Innovation", logo: "💎", year: 1987, founder: "Bernard Arnault", bn: 1, z: "capricorn", kw: ["luxury","conglomerate","heritage","excellence","prestige"], lc: ["#000000","#FFFFFF"], ln: [1,4,8,9], energy: "The Emperor — commands the luxury world with ambition and vision" },
  { id: "cartier", name: "Cartier", slug: "cartier", cat: "luxury", desc: "French jewelry and watchmaking maison, known as the jeweler of kings. Creator of the iconic Love bracelet and Tank watch.", tagline: "The Maison of Wonders", logo: "💍", year: 1847, founder: "Louis-François Cartier", bn: 2, z: "libra", kw: ["jewelry","craftsmanship","heritage","luxury","elegance"], lc: ["#FF0000","#FFD700"], ln: [2,4,6,8], energy: "The Artist — creates wearable masterpieces of timeless beauty" },
  { id: "rolex", name: "Rolex", slug: "rolex", cat: "luxury", desc: "Swiss luxury watchmaker synonymous with prestige, precision, and achievement. The ultimate symbol of success.", tagline: "A Crown for Every Achievement", logo: "⌚", year: 1905, founder: "Hans Wilsdorf, Alfred Davis", bn: 2, z: "capricorn", kw: ["watches","precision","luxury","status","achievement"], lc: ["#006039","#FFD700"], ln: [2,4,6,8], energy: "The Achiever — measures success with precision and permanence" },
  { id: "tiffany", name: "Tiffany & Co.", slug: "tiffany", cat: "luxury", desc: "American luxury jewelry house famous for diamond engagement rings, Tiffany Blue, and timeless elegance.", tagline: "The Romance of Tiffany", logo: "💙", year: 1837, founder: "Charles Lewis Tiffany", bn: 9, z: "libra", kw: ["jewelry","romance","elegance","craftsmanship","tradition"], lc: ["#81D8D0","#000000"], ln: [9,2,3,6], energy: "The Romantic — celebrates love with exquisite beauty and grace" },
  { id: "omega", name: "Omega", slug: "omega", cat: "luxury", desc: "Swiss luxury watchmaker known for precision, space exploration heritage (Moonwatch), and James Bond association.", tagline: "The Official Timekeeper of the Olympics", logo: "⌚", year: 1848, founder: "Louis Brandt", bn: 5, z: "sagittarius", kw: ["watches","precision","adventure","heritage","exploration"], lc: ["#000000","#FFFFFF"], ln: [5,1,3,8], energy: "The Explorer — measures time for history-making moments" },
  // === BEAUTY ===
  { id: "loreal", name: "L'Oréal", slug: "loreal", cat: "beauty", desc: "World's largest cosmetics and beauty company, pioneering haircolor, skincare, and makeup innovation for all.", tagline: "Because You're Worth It", logo: "💄", year: 1909, founder: "Eugène Schueller", bn: 9, z: "taurus", kw: ["beauty","innovation","cosmetics","skincare","inclusivity"], lc: ["#000000","#FFD700"], ln: [9,2,4,6], energy: "The Transformer — empowers beauty and confidence worldwide" },
  { id: "estee-lauder", name: "Estée Lauder", slug: "estee-lauder", cat: "beauty", desc: "American prestige cosmetics company known for luxury skincare, makeup, and fragrance brands.", tagline: "Bringing the Best to Everyone We Touch", logo: "✨", year: 1946, founder: "Estée Lauder, Joseph Lauder", bn: 7, z: "libra", kw: ["luxury","skincare","beauty","elegance","prestige"], lc: ["#003399","#000000"], ln: [7,2,4,6], energy: "The Refiner — perfects beauty through elegance and innovation" },
  { id: "sephora", name: "Sephora", slug: "sephora", cat: "beauty", desc: "Global beauty retail destination offering curated cosmetics, skincare, and fragrance from hundreds of brands.", tagline: "The Beauty Authority", logo: "💋", year: 1970, founder: "Dominique Mandonnaud", bn: 1, z: "libra", kw: ["beauty","retail","cosmetics","discovery","community"], lc: ["#000000","#FFFFFF"], ln: [1,3,5,7], energy: "The Curator — brings the world's beauty to your fingertips" },
  { id: "lancome", name: "Lancôme", slug: "lancome", cat: "beauty", desc: "French luxury beauty brand offering premium skincare, makeup, and fragrances. Embodies Parisian elegance.", tagline: "La vie est belle", logo: "🌹", year: 1935, founder: "Armand Petitjean", bn: 9, z: "libra", kw: ["skincare","makeup","fragrance","luxury","elegance"], lc: ["#000000","#FFCB08"], ln: [9,2,4,6], energy: "The Elegant — embodies Parisian beauty and refinement" },
  // === ENTERTAINMENT ===
  { id: "disney", name: "Disney", slug: "disney", cat: "entertainment", desc: "The world's most magical entertainment company. Creator of beloved characters, theme parks, and timeless stories.", tagline: "The Happiest Place on Earth", logo: "🏰", year: 1923, founder: "Walt Disney, Roy O. Disney", bn: 4, z: "cancer", kw: ["magic","stories","family","imagination","nostalgia"], lc: ["#000000","#FFFFFF"], ln: [4,2,6,9], energy: "The Magician — creates worlds of wonder and imagination" },
  { id: "sony", name: "Sony", slug: "sony", cat: "entertainment", desc: "Japanese electronics and entertainment conglomerate behind PlayStation, Walkman, cameras, and blockbuster movies.", tagline: "Make Believe", logo: "🎮", year: 1946, founder: "Masaru Ibuka, Akio Morita", bn: 1, z: "gemini", kw: ["electronics","gaming","entertainment","innovation","technology"], lc: ["#000000","#FFFFFF"], ln: [1,3,5,7], energy: "The Inventor — brings imagination to life through technology" },
  { id: "nintendo", name: "Nintendo", slug: "nintendo", cat: "entertainment", desc: "Japanese video game pioneer responsible for Mario, Zelda, Pokémon, and countless hours of joyful play.", tagline: "If You Play, You Belong", logo: "🎮", year: 1889, founder: "Fusajiro Yamauchi", bn: 5, z: "cancer", kw: ["gaming","nostalgia","innovation","fun","family"], lc: ["#E60012","#000000"], ln: [5,3,7,9], energy: "The Joybringer — fills the world with wonder and playful delight" },
  { id: "warner-bros", name: "Warner Bros.", slug: "warner-bros", cat: "entertainment", desc: "Legendary film and television studio behind Harry Potter, DC Comics, and iconic entertainment franchises.", tagline: "If It Matters, It's on Warner Bros.", logo: "🎬", year: 1923, founder: "Harry, Albert, Sam, and Jack Warner", bn: 7, z: "leo", kw: ["movies","entertainment","stories","franchises","creativity"], lc: ["#000000","#FFD700"], ln: [7,1,3,5], energy: "The Storyteller — captivates audiences with epic narratives" },
  { id: "universal", name: "Universal", slug: "universal", cat: "entertainment", desc: "Major film studio and theme park operator behind Jurassic Park, Fast & Furious, and Minions.", tagline: "The World Is Yours", logo: "🌍", year: 1912, founder: "Carl Laemmle", bn: 4, z: "aquarius", kw: ["movies","entertainment","parks","franchises","spectacle"], lc: ["#000000","#FFD700"], ln: [4,1,5,7], energy: "The Spectacle — creates larger-than-life cinematic experiences" },
  { id: "bbc", name: "BBC", slug: "bbc", cat: "entertainment", desc: "British public service broadcaster, trusted source of news, education, and world-class programming for a century.", tagline: "Nation Shall Speak Peace Unto Nation", logo: "📺", year: 1922, founder: "John Reith", bn: 7, z: "virgo", kw: ["news","education","trust","quality","public-service"], lc: ["#000000","#FFFFFF"], ln: [7,2,4,6], energy: "The Informer — educates and informs with integrity and precision" },
  { id: "national-geographic", name: "National Geographic", slug: "national-geographic", cat: "entertainment", desc: "Iconic institution exploring and protecting our planet through science, exploration, education, and storytelling.", tagline: "Science, Exploration, Storytelling", logo: "🌎", year: 1888, founder: "Alexander Graham Bell, Gardiner Greene Hubbard", bn: 4, z: "sagittarius", kw: ["exploration","science","nature","education","discovery"], lc: ["#FFCC00","#000000"], ln: [4,2,5,7], energy: "The Explorer — ventures to the edges of knowledge and beyond" },
  // === SPORTS ===
  { id: "puma", name: "Puma", slug: "puma", cat: "sports", desc: "German sportswear brand fusing athletic performance with streetwear style. Known for iconic cat logo and lifestyle collaborations.", tagline: "Forever Faster", logo: "🐆", year: 1948, founder: "Rudolf Dassler", bn: 6, z: "sagittarius", kw: ["sportswear","speed","performance","style","collaboration"], lc: ["#000000","#FF0000"], ln: [6,2,4,8], energy: "The Sprinter — moves fast and breaks boundaries" },
  { id: "under-armour", name: "Under Armour", slug: "under-armour", cat: "sports", desc: "American sportswear company known for performance apparel that keeps athletes cool, dry, and light.", tagline: "I Will", logo: "💪", year: 1996, founder: "Kevin Plank", bn: 4, z: "aries", kw: ["performance","training","innovation","athletics","toughness"], lc: ["#000000","#A8A9AD"], ln: [4,1,3,8], energy: "The Warrior — empowers athletes with unyielding determination" },
  { id: "the-north-face", name: "The North Face", slug: "the-north-face", cat: "sports", desc: "Outdoor apparel and equipment brand built for exploration, adventure, and the world's harshest environments.", tagline: "Never Stop Exploring", logo: "🧗", year: 1966, founder: "Doug Tompkins, Susie Tompkins Buell", bn: 6, z: "sagittarius", kw: ["outdoor","exploration","adventure","performance","nature"], lc: ["#000000","#FFFFFF"], ln: [6,3,5,9], energy: "The Adventurer — pushes beyond boundaries into the wild unknown" },
  { id: "patagonia", name: "Patagonia", slug: "patagonia", cat: "sports", desc: "Outdoor clothing company committed to environmental activism, quality gear, and sustainable business practices.", tagline: "We're in Business to Save Our Home Planet", logo: "🏔️", year: 1973, founder: "Yvon Chouinard", bn: 3, z: "aquarius", kw: ["outdoor","sustainability","activism","quality","environment"], lc: ["#0C4A34","#FFFFFF"], ln: [3,5,7,9], energy: "The Activist — protects the planet with purpose-driven commerce" },
  // === FINANCE ===
  { id: "goldman-sachs", name: "Goldman Sachs", slug: "goldman-sachs", cat: "finance", desc: "Leading global investment bank and financial services firm advising corporations, governments, and institutions.", tagline: "The Goldman Sachs Advantage", logo: "🏛️", year: 1869, founder: "Marcus Goldman, Samuel Sachs", bn: 8, z: "capricorn", kw: ["investment","banking","finance","wealth","strategy"], lc: ["#003087","#000000"], ln: [8,2,4,6], energy: "The Strategist — masters wealth and power with disciplined precision" },
  { id: "visa", name: "Visa", slug: "visa", cat: "finance", desc: "Global digital payments leader connecting consumers, merchants, and financial institutions across 200+ countries.", tagline: "Everywhere You Want to Be", logo: "💳", year: 1958, founder: "Dee Hock", bn: 6, z: "gemini", kw: ["payments","digital","global","connectivity","innovation"], lc: ["#1A1F71","#FFFFFF"], ln: [6,2,4,8], energy: "The Connector — facilitates the flow of commerce worldwide" },
  { id: "mastercard", name: "Mastercard", slug: "mastercard", cat: "finance", desc: "Global payments technology company enabling secure, seamless transactions for consumers and businesses.", tagline: "There Are Some Things Money Can't Buy. For Everything Else, There's Mastercard.", logo: "💳", year: 1966, founder: "Interbank Card Association", bn: 3, z: "gemini", kw: ["payments","technology","global","security","innovation"], lc: ["#EB001B","#F79E1B"], ln: [3,5,7,9], energy: "The Bridge — connects people and possibilities through commerce" },
  { id: "american-express", name: "American Express", slug: "american-express", cat: "finance", desc: "Premium financial services and charge card company known for exceptional customer service and travel benefits.", tagline: "Don't Leave Home Without It", logo: "💳", year: 1850, founder: "Henry Wells, William Fargo, John Butterfield", bn: 8, z: "capricorn", kw: ["premium","service","travel","finance","trust"], lc: ["#002663","#FFFFFF"], ln: [8,2,4,6], energy: "The Guardian — protects and serves with premium excellence" },
  { id: "paypal", name: "PayPal", slug: "paypal", cat: "finance", desc: "Digital payments pioneer enabling global online transactions, money transfers, and financial services.", tagline: "The New Way to Pay", logo: "💸", year: 1998, founder: "Max Levchin, Peter Thiel, Luke Nosek, Ken Howery, Elon Musk", bn: 8, z: "aquarius", kw: ["payments","digital","innovation","global","fintech"], lc: ["#003087","#009CDE"], ln: [8,1,3,5], energy: "The Disruptor — reinvented money for the digital age" },
  { id: "bloomberg", name: "Bloomberg", slug: "bloomberg", cat: "finance", desc: "Global financial data, news, and analytics company powering the world's financial markets.", tagline: "The World's Most Powerful Data Platform", logo: "📊", year: 1981, founder: "Michael Bloomberg, Thomas Secunda", bn: 8, z: "virgo", kw: ["data","finance","news","analytics","technology"], lc: ["#E31C25","#000000"], ln: [8,2,4,7], energy: "The Analyst — transforms data into actionable intelligence" },
  // === TRAVEL & HOSPITALITY ===
  { id: "hilton", name: "Hilton", slug: "hilton", cat: "travel-hospitality", desc: "Global hospitality company operating thousands of hotels worldwide, known for warm hospitality and quality accommodations.", tagline: "Travel Should Be Human. Again.", logo: "🏨", year: 1919, founder: "Conrad Hilton", bn: 33, z: "cancer", kw: ["hospitality","hotels","travel","comfort","service"], lc: ["#00205B","#FFFFFF"], ln: [33,2,4,6], energy: "The Host — welcomes the world with warmth and grace" },
  { id: "marriott", name: "Marriott", slug: "marriott", cat: "travel-hospitality", desc: "Leading global lodging company with iconic hotel brands serving travelers worldwide.", tagline: "Travel Brilliantly", logo: "🏨", year: 1927, founder: "J. Willard Marriott", bn: 6, z: "taurus", kw: ["hotels","hospitality","travel","luxury","comfort"], lc: ["#004C97","#000000"], ln: [6,2,4,8], energy: "The Host — creates home away from home with consistent quality" },
  { id: "emirates", name: "Emirates", slug: "emirates", cat: "travel-hospitality", desc: "Dubai-based premium airline redefining air travel with luxury, innovation, and world-class service.", tagline: "Hello Tomorrow", logo: "✈️", year: 1985, founder: "Ahmed bin Saeed Al Maktoum", bn: 9, z: "sagittarius", kw: ["aviation","luxury","travel","innovation","service"], lc: ["#D71921","#000000"], ln: [9,3,5,8], energy: "The Voyager — elevates travel to an art form" },
  { id: "delta", name: "Delta Air Lines", slug: "delta", cat: "travel-hospitality", desc: "Major American airline with a reputation for operational excellence, customer service, and global connectivity.", tagline: "Keep Climbing", logo: "✈️", year: 1925, founder: "C.E. Woolman", bn: 6, z: "capricorn", kw: ["aviation","travel","reliability","service","connectivity"], lc: ["#003366","#FFFFFF"], ln: [6,2,4,7], energy: "The Climber — ascends to excellence through discipline and perseverance" },
  { id: "airbnb", name: "Airbnb", slug: "airbnb", cat: "travel-hospitality", desc: "Peer-to-peer lodging marketplace that revolutionized travel by connecting guests with unique accommodations worldwide.", tagline: "Belong Anywhere", logo: "🏡", year: 2008, founder: "Brian Chesky, Joe Gebbia, Nathan Blecharczyk", bn: 1, z: "aquarius", kw: ["travel","community","sharing-economy","innovation","hospitality"], lc: ["#FF5A5F","#000000"], ln: [1,3,5,9], energy: "The Community Builder — connects travelers through shared experiences" },
  // === RETAIL ===
  { id: "ikea", name: "IKEA", slug: "ikea", cat: "retail", desc: "Swedish home furnishings giant democratizing design with affordable, flat-packed furniture and modern style.", tagline: "To Create a Better Everyday Life for the Many People", logo: "🛋️", year: 1943, founder: "Ingvar Kamprad", bn: 8, z: "capricorn", kw: ["furniture","design","affordable","home","innovation"], lc: ["#0051A1","#FFCC00"], ln: [8,2,4,6], energy: "The Democratizer — makes good design accessible to everyone" },
  { id: "walmart", name: "Walmart", slug: "walmart", cat: "retail", desc: "World's largest retailer, offering everyday low prices with massive scale, supply chain excellence, and community focus.", tagline: "Save Money. Live Better.", logo: "🛒", year: 1962, founder: "Sam Walton", bn: 7, z: "taurus", kw: ["retail","value","scale","logistics","community"], lc: ["#007DC6","#FFC120"], ln: [7,4,6,8], energy: "The Provider — delivers value at an unprecedented scale" },
  { id: "costco", name: "Costco", slug: "costco", cat: "retail", desc: "Membership warehouse club offering exceptional value through bulk buying, quality products, and employee-centric culture.", tagline: "The Smart Place to Shop", logo: "🛍️", year: 1976, founder: "Sol Price, Jim Sinegal", bn: 3, z: "taurus", kw: ["retail","value","quality","membership","efficiency"], lc: ["#005293","#FF0000"], ln: [3,4,6,8], energy: "The Value Creator — proves that quality and value go hand in hand" },
  { id: "ebay", name: "eBay", slug: "ebay", cat: "retail", desc: "Global online marketplace connecting buyers and sellers. Pioneer of peer-to-peer e-commerce and online auctions.", tagline: "Buy It. Sell It. Love It.", logo: "🏪", year: 1995, founder: "Pierre Omidyar", bn: 6, z: "gemini", kw: ["marketplace","ecommerce","auction","community","second-hand"], lc: ["#E53238","#0064D2"], ln: [6,2,3,5], energy: "The Marketplace — connects millions of buyers and sellers worldwide" },
  { id: "target", name: "Target", slug: "target", cat: "retail", desc: "American retail giant known for stylish, affordable products, exceptional design collaborations, and community focus.", tagline: "Expect More. Pay Less.", logo: "🎯", year: 1902, founder: "George Dayton", bn: 8, z: "libra", kw: ["retail","design","affordable","style","community"], lc: ["#CC0000","#FFFFFF"], ln: [8,2,4,6], energy: "The Curator — brings great design to everyday shopping" },
  // === TECHNOLOGY (more) ===
  { id: "uber", name: "Uber", slug: "uber", cat: "technology", desc: "Ride-hailing and mobility platform that transformed urban transportation through technology and on-demand service.", tagline: "Move the Way You Want", logo: "🚗", year: 2009, founder: "Travis Kalanick, Garrett Camp", bn: 1, z: "aquarius", kw: ["mobility","transportation","innovation","on-demand","disruption"], lc: ["#000000","#FFFFFF"], ln: [1,3,5,8], energy: "The Disruptor — reinvented urban mobility on a global scale" },
  { id: "spacex", name: "SpaceX", slug: "spacex", cat: "technology", desc: "Space exploration company revolutionizing space travel with reusable rockets and the mission to make humanity multiplanetary.", tagline: "Making Humanity Multiplanetary", logo: "🚀", year: 2002, founder: "Elon Musk", bn: 5, z: "sagittarius", kw: ["space","exploration","innovation","rockets","ambition"], lc: ["#000000","#FFFFFF"], ln: [5,1,3,9], energy: "The Explorer — reaches for the stars with audacious vision" },
  { id: "nvidia", name: "NVIDIA", slug: "nvidia", cat: "technology", desc: "AI computing leader powering the next industrial revolution through GPUs, accelerated computing, and artificial intelligence.", tagline: "The AI Computing Company", logo: "🖥️", year: 1993, founder: "Jensen Huang, Chris Malachowsky, Curtis Priem", bn: 5, z: "aquarius", kw: ["AI","graphics","computing","innovation","gaming"], lc: ["#76B900","#000000"], ln: [5,1,3,7], energy: "The Visionary — powers the AI revolution with relentless innovation" },
  { id: "intel", name: "Intel", slug: "intel", cat: "technology", desc: "Semiconductor pioneer that powered the personal computer revolution and continues driving computing innovation.", tagline: "Intel Inside", logo: "💻", year: 1968, founder: "Gordon Moore, Robert Noyce, Andrew Grove", bn: 6, z: "capricorn", kw: ["processors","semiconductors","innovation","computing","infrastructure"], lc: ["#0071C5","#000000"], ln: [6,2,4,8], energy: "The Foundation — built the computing infrastructure of the modern world" },
  { id: "amd", name: "AMD", slug: "amd", cat: "technology", desc: "Semiconductor company driving high-performance computing with CPUs, GPUs, and innovative chiplet architectures.", tagline: "The Performance Computing Leader", logo: "💻", year: 1969, founder: "Jerry Sanders", bn: 9, z: "aries", kw: ["processors","graphics","performance","innovation","competition"], lc: ["#ED1C24","#000000"], ln: [9,1,3,5], energy: "The Challenger — competes fiercely and punches above its weight" },
  { id: "ibm", name: "IBM", slug: "ibm", cat: "technology", desc: "Century-old technology pioneer evolving from mainframes to AI and quantum computing. Consulting and enterprise solutions.", tagline: "Let's Create Something That Changes Everything", logo: "🖥️", year: 1911, founder: "Charles Flint", bn: 6, z: "capricorn", kw: ["enterprise","AI","consulting","innovation","cloud"], lc: ["#006699","#000000"], ln: [6,1,4,8], energy: "The Elder — adapts and endures through a century of change" },
  { id: "huawei", name: "Huawei", slug: "huawei", cat: "technology", desc: "Chinese technology giant leading in telecommunications equipment, smartphones, and 5G innovation.", tagline: "Building a Fully Connected, Intelligent World", logo: "📱", year: 1987, founder: "Ren Zhengfei", bn: 4, z: "capricorn", kw: ["telecom","smartphones","5G","infrastructure","innovation"], lc: ["#FF0000","#000000"], ln: [4,1,6,8], energy: "The Builder — constructs the infrastructure of a connected world" },
  { id: "xiaomi", name: "Xiaomi", slug: "xiaomi", cat: "technology", desc: "Chinese electronics company disrupting markets with premium features at accessible prices. Smartphones, AIoT, and smart devices.", tagline: "Innovation for Everyone", logo: "📱", year: 2010, founder: "Lei Jun", bn: 8, z: "gemini", kw: ["smartphones","innovation","value","AIoT","ecosystem"], lc: ["#FF6700","#000000"], ln: [8,1,3,5], energy: "The Disruptor — democratizes premium technology for the masses" },
  { id: "hp", name: "HP", slug: "hp", cat: "technology", desc: "Pioneering technology company powering the world's computing needs with PCs, printers, and enterprise solutions.", tagline: "Keep Reinventing", logo: "💻", year: 1939, founder: "Bill Hewlett, David Packard", bn: 6, z: "capricorn", kw: ["computers","printing","innovation","enterprise","reliability"], lc: ["#0096D6","#000000"], ln: [6,2,4,7], energy: "The Workhorse — keeps business running with reliable technology" },
  { id: "dell", name: "Dell", slug: "dell", cat: "technology", desc: "Computer technology company known for direct-to-consumer PC sales, enterprise solutions, and supply chain innovation.", tagline: "The Power to Do More", logo: "💻", year: 1984, founder: "Michael Dell", bn: 6, z: "virgo", kw: ["computers","enterprise","direct-sales","innovation","reliability"], lc: ["#007DB8","#000000"], ln: [6,2,4,8], energy: "The Efficient — built a global empire on supply chain mastery" },
  { id: "canon", name: "Canon", slug: "canon", cat: "technology", desc: "Japanese imaging and optical products leader, renowned for cameras, printers, and medical equipment.", tagline: "Delighting You Always", logo: "📷", year: 1937, founder: "Takeshi Mitarai", bn: 2, z: "virgo", kw: ["cameras","imaging","precision","quality","innovation"], lc: ["#000000","#FFFFFF"], ln: [2,4,6,8], energy: "The Precisionist — captures moments with technical excellence" },
  // === TECHNOLOGY (more) ===
  { id: "oracle", name: "Oracle", slug: "oracle", cat: "technology", desc: "Enterprise software giant powering the world's databases, cloud infrastructure, and business applications.", tagline: "Integrated Cloud Applications and Platform Services", logo: "☁️", year: 1977, founder: "Larry Ellison, Bob Miner, Ed Oates", bn: 9, z: "capricorn", kw: ["database","cloud","enterprise","software","infrastructure"], lc: ["#F80000","#000000"], ln: [9,2,4,7], energy: "The Guardian — holds the world's data with unmatched reliability" },
  { id: "salesforce", name: "Salesforce", slug: "salesforce", cat: "technology", desc: "Cloud-based CRM pioneer transforming customer relationships through AI-powered sales, service, and marketing.", tagline: "The World's #1 AI CRM", logo: "☁️", year: 1999, founder: "Marc Benioff, Parker Harris", bn: 4, z: "gemini", kw: ["CRM","cloud","AI","enterprise","customer"], lc: ["#00A1E0","#FFFFFF"], ln: [4,1,6,8], energy: "The Connector — unites businesses with their customers through intelligent CRM" },
  { id: "cisco", name: "Cisco", slug: "cisco", cat: "technology", desc: "Global networking hardware and software leader powering the internet infrastructure with routers, switches, and security solutions.", tagline: "The Bridge to Possible", logo: "🌐", year: 1984, founder: "Leonard Bosack, Sandy Lerner", bn: 22, z: "capricorn", kw: ["networking","security","infrastructure","enterprise","internet"], lc: ["#1BA0D7","#000000"], ln: [22,2,4,8], energy: "The Backbone — powers the internet with unmatched networking expertise" },
  { id: "adobe", name: "Adobe", slug: "adobe", cat: "technology", desc: "Creative software pioneer whose tools power digital design, document management, and marketing across every screen.", tagline: "Creativity for All", logo: "🎨", year: 1982, founder: "John Warnock, Charles Geschke", bn: 9, z: "pisces", kw: ["creative","design","software","cloud","digital"], lc: ["#FF0000","#000000"], ln: [9,3,5,7], energy: "The Creator — empowers digital creativity across every medium" },
  { id: "twitter", name: "Twitter / X", slug: "twitter", cat: "technology", desc: "Global microblogging and social networking platform that redefined real-time public conversation and news distribution.", tagline: "The Digital Town Square", logo: "🐦", year: 2006, founder: "Jack Dorsey, Biz Stone, Evan Williams", bn: 7, z: "gemini", kw: ["social","news","real-time","communication","public"], lc: ["#000000","#FFFFFF"], ln: [7,2,3,5], energy: "The Broadcaster — amplifies voices in real-time across the globe" },
  { id: "snapchat", name: "Snapchat", slug: "snapchat", cat: "technology", desc: "Multimedia messaging app pioneering ephemeral content, augmented reality, and mobile-first social interaction.", tagline: "The Fastest Way to Share a Moment", logo: "👻", year: 2011, founder: "Evan Spiegel, Bobby Murphy, Reggie Brown", bn: 5, z: "aquarius", kw: ["social","AR","messaging","camera","youth"], lc: ["#FFFC00","#000000"], ln: [5,1,3,9], energy: "The Ephemerist — captures fleeting moments with playful innovation" },
  { id: "pinterest", name: "Pinterest", slug: "pinterest", cat: "technology", desc: "Visual discovery engine helping users find ideas and inspiration for their projects, hobbies, and life goals.", tagline: "Discover Ideas", logo: "📌", year: 2010, founder: "Ben Silbermann, Paul Sciarra, Evan Sharp", bn: 9, z: "libra", kw: ["discovery","visual","inspiration","creative","lifestyle"], lc: ["#E60023","#FFFFFF"], ln: [9,2,4,6], energy: "The Curator — inspires through beautiful visual discovery" },
  { id: "tiktok", name: "TikTok", slug: "tiktok", cat: "technology", desc: "Short-form video platform that transformed entertainment, culture, and content creation with addictive algorithmic discovery.", tagline: "Make Your Day", logo: "🎵", year: 2016, founder: "Zhang Yiming", bn: 5, z: "aquarius", kw: ["video","social","entertainment","viral","creative"], lc: ["#000000","#FFFFFF"], ln: [5,1,3,7], energy: "The Trendsetter — shapes global culture through viral short-form video" },
  { id: "tencent", name: "Tencent", slug: "tencent", cat: "technology", desc: "Chinese internet and technology conglomerate behind WeChat, gaming, payments, and a vast digital ecosystem.", tagline: "Value for Users, Technology for Good", logo: "🐧", year: 1998, founder: "Ma Huateng, Zhang Zhidong", bn: 9, z: "capricorn", kw: ["social","gaming","payments","ecosystem","China"], lc: ["#00A1E9","#FFFFFF"], ln: [9,2,4,8], energy: "The Giant — powers China's digital ecosystem with unmatched scale" },
  { id: "alibaba", name: "Alibaba", slug: "alibaba", cat: "technology", desc: "Chinese e-commerce and technology conglomerate revolutionizing global trade through digital marketplaces and cloud computing.", tagline: "To Make It Easy to Do Business Anywhere", logo: "🌐", year: 1999, founder: "Jack Ma", bn: 1, z: "sagittarius", kw: ["ecommerce","marketplace","cloud","logistics","China"], lc: ["#FF6A00","#000000"], ln: [1,3,5,8], energy: "The Pioneer — opened global trade through digital marketplaces" },
  { id: "baidu", name: "Baidu", slug: "baidu", cat: "technology", desc: "Leading Chinese search engine and AI company driving innovation in autonomous driving, voice recognition, and deep learning.", tagline: "Baidu, a Know-ledgeable Choice", logo: "🔍", year: 2000, founder: "Robin Li, Eric Xu", bn: 1, z: "gemini", kw: ["search","AI","autonomous","China","technology"], lc: ["#2932E1","#FFFFFF"], ln: [1,4,6,9], energy: "The Searcher — organizes China's digital information with AI power" },
  { id: "shopify", name: "Shopify", slug: "shopify", cat: "technology", desc: "E-commerce platform empowering millions of merchants to build, manage, and grow their online stores with ease.", tagline: "Make Commerce Better for Everyone", logo: "🛍️", year: 2004, founder: "Tobias Lütke, Daniel Weinand, Scott Lake", bn: 8, z: "libra", kw: ["ecommerce","retail","entrepreneurship","platform","DTC"], lc: ["#96BF48","#FFFFFF"], ln: [8,2,4,6], energy: "The Enabler — empowers anyone to start and grow an online business" },
  { id: "stripe", name: "Stripe", slug: "stripe", cat: "technology", desc: "Online payment infrastructure platform powering internet commerce for businesses of all sizes with developer-first tools.", tagline: "The Payment Infrastructure for the Internet", logo: "💳", year: 2010, founder: "Patrick Collison, John Collison", bn: 33, z: "gemini", kw: ["payments","infrastructure","developer","fintech","API"], lc: ["#635BFF","#FFFFFF"], ln: [33,2,4,8], energy: "The Architect — built the payment infrastructure for the internet economy" },
  { id: "square", name: "Square", slug: "square", cat: "technology", desc: "Financial services and mobile payment company empowering small businesses with accessible commerce tools and hardware.", tagline: "Square makes commerce easy", logo: "📱", year: 2009, founder: "Jack Dorsey, Jim McKelvey", bn: 9, z: "aquarius", kw: ["payments","small-business","hardware","fintech","POS"], lc: ["#000000","#FFFFFF"], ln: [9,1,3,5], energy: "The Democratizer — made payment processing accessible for every small business" },
  { id: "asus", name: "ASUS", slug: "asus", cat: "technology", desc: "Taiwanese multinational computer and phone hardware company known for motherboards, gaming laptops, and innovative electronics.", tagline: "In Search of Incredible", logo: "💻", year: 1989, founder: "T.H. Tung, Ted Hsu, Wayne Hsieh, M.T. Liao", bn: 6, z: "capricorn", kw: ["hardware","gaming","laptops","motherboard","PC"], lc: ["#000000","#FFFFFF"], ln: [6,2,4,7], energy: "The Builder — crafts premium hardware for gamers and creators" },
  { id: "panasonic", name: "Panasonic", slug: "panasonic", cat: "technology", desc: "Japanese electronics corporation powering consumer lifestyles and business solutions with innovative products and sustainability.", tagline: "A Better Life, A Better World", logo: "📺", year: 1918, founder: "Konosuke Matsushita", bn: 2, z: "taurus", kw: ["electronics","home","batteries","appliances","automotive"], lc: ["#004272","#FFFFFF"], ln: [2,4,6,8], energy: "The Steadfast — delivers reliable innovation across generations" },
  { id: "arm", name: "ARM", slug: "arm", cat: "technology", desc: "British semiconductor and software design company whose chip architecture powers nearly every smartphone on the planet.", tagline: "The Architecture for the Digital World", logo: "🔧", year: 1990, founder: "Robin Saxby, Jamie Urquhart, Mike Muller, Tudor Brown", bn: 5, z: "virgo", kw: ["semiconductor","architecture","mobile","licensing","processors"], lc: ["#0091BD","#FFFFFF"], ln: [5,2,4,7], energy: "The Silent Engine — powers billions of devices worldwide" },
  { id: "servicenow", name: "ServiceNow", slug: "servicenow", cat: "technology", desc: "Cloud-based workflow automation platform transforming enterprise IT, employee, and customer service operations.", tagline: "Made for the Modern Enterprise", logo: "⚙️", year: 2004, founder: "Fred Luddy", bn: 7, z: "capricorn", kw: ["workflow","automation","enterprise","IT","cloud"], lc: ["#81BC5E","#FFFFFF"], ln: [7,2,4,8], energy: "The Optimizer — streamlines enterprise workflows at massive scale" },
  { id: "intuit", name: "Intuit", slug: "intuit", cat: "technology", desc: "Financial software company behind TurboTax, QuickBooks, and Mint, empowering individuals and small businesses with financial tools.", tagline: "Powering Prosperity Around the World", logo: "💰", year: 1983, founder: "Scott Cook, Tom Proulx", bn: 3, z: "taurus", kw: ["finance","software","tax","accounting","small-business"], lc: ["#0077C5","#FFFFFF"], ln: [3,1,4,8], energy: "The Simplifier — makes financial management accessible for everyone" },
  { id: "palantir", name: "Palantir Technologies", slug: "palantir", cat: "technology", desc: "Data analytics company building software platforms for counterterrorism, defense, healthcare, and enterprise intelligence.", tagline: "The Operating System for the Modern Enterprise", logo: "🔮", year: 2003, founder: "Peter Thiel, Alex Karp, Stephen Cohen, Nathan Gettings, Eric Weinstein, Matt Ocko", bn: 1, z: "scorpio", kw: ["data","analytics","defense","AI","enterprise"], lc: ["#101010","#FFFFFF"], ln: [1,2,4,8], energy: "The Visionary — sees patterns others miss and turns data into decisions" },
  { id: "snowflake", name: "Snowflake", slug: "snowflake", cat: "technology", desc: "Cloud-based data warehousing platform enabling businesses to store, analyze, and share data with unprecedented scale and speed.", tagline: "The Data Cloud", logo: "❄️", year: 2012, founder: "Benoît Dageville, Thierry Cruanes, Marcin Żukowski", bn: 7, z: "aquarius", kw: ["data","cloud","warehouse","analytics","database"], lc: ["#00BFFF","#FFFFFF"], ln: [7,1,3,9], energy: "The Architect — builds the foundation for modern data-driven enterprises" },
  { id: "mariadb", name: "MariaDB", slug: "mariadb", cat: "technology", desc: "Open-source relational database management system forked from MySQL, known for reliability, performance, and community-driven development.", tagline: "The Open Source Database", logo: "🐬", year: 2009, founder: "Michael Widenius", bn: 1, z: "aquarius", kw: ["database","open-source","MySQL","relational","community"], lc: ["#003545","#FFFFFF"], ln: [1,4,6,8], energy: "The Free — champions open-source database innovation for everyone" },
  // === AUTOMOTIVE (more) ===
  { id: "bugatti", name: "Bugatti", slug: "bugatti", cat: "automotive", desc: "French ultra-luxury hypercar manufacturer crafting the world's fastest and most exclusive automobiles with artisanal precision.", tagline: "Create the Incomparable", logo: "🏎️", year: 1909, founder: "Ettore Bugatti", bn: 8, z: "leo", kw: ["hypercar","luxury","speed","excellence","exclusivity"], lc: ["#002654","#FFFFFF"], ln: [8,1,3,5], energy: "The Magnificent — pushes automotive engineering to its absolute peak" },
  { id: "aston-martin", name: "Aston Martin", slug: "aston-martin", cat: "automotive", desc: "British luxury sports car manufacturer synonymous with elegance, performance, and James Bond's iconic ride.", tagline: "The Power, Beauty and Soul of British Luxury", logo: "🚗", year: 1913, founder: "Lionel Martin, Robert Bamford", bn: 9, z: "libra", kw: ["luxury","sports-car","British","elegance","heritage"], lc: ["#006650","#FFFFFF"], ln: [9,2,4,6], energy: "The Icon — embodies British luxury and performance excellence" },
  { id: "maserati", name: "Maserati", slug: "maserati", cat: "automotive", desc: "Italian luxury sports car manufacturer renowned for exquisite design, powerful engines, and racing heritage.", tagline: "The Maserati of SUVs", logo: "🚗", year: 1914, founder: "Alfieri Maserati", bn: 5, z: "leo", kw: ["luxury","Italian","sports-car","design","performance"], lc: ["#0A2540","#FFFFFF"], ln: [5,1,4,8], energy: "The Artisan — blends Italian artistry with racing soul" },
  { id: "mclaren", name: "McLaren", slug: "mclaren", cat: "automotive", desc: "British automotive and motorsport company known for Formula 1 excellence and cutting-edge hypercar engineering.", tagline: "Driven by Performance, Perfected by Engineering", logo: "🏎️", year: 1963, founder: "Bruce McLaren", bn: 3, z: "aries", kw: ["F1","hypercar","racing","engineering","innovation"], lc: ["#FF6400","#FFFFFF"], ln: [3,5,7,9], energy: "The Racer — born on the track, engineered for excellence" },
  { id: "rolls-royce", name: "Rolls-Royce", slug: "rolls-royce", cat: "automotive", desc: "Ultra-luxury automotive manufacturer crafting the world's most refined automobiles with bespoke craftsmanship.", tagline: "Strive for Perfection", logo: "🚗", year: 1906, founder: "Charles Rolls, Henry Royce", bn: 7, z: "cancer", kw: ["luxury","bespoke","craftsmanship","heritage","excellence"], lc: ["#003B5C","#FFFFFF"], ln: [7,2,4,6], energy: "The Connoisseur — sets the standard for automotive luxury and refinement" },
  { id: "bentley", name: "Bentley", slug: "bentley", cat: "automotive", desc: "British luxury automobile manufacturer blending handcrafted opulence with grand touring performance.", tagline: "Be Extraordinary", logo: "🚗", year: 1919, founder: "W.O. Bentley", bn: 2, z: "cancer", kw: ["luxury","British","handcrafted","heritage","grand-tourer"], lc: ["#006747","#FFFFFF"], ln: [2,4,6,8], energy: "The Aristocrat — defines grand touring with handcrafted luxury" },
  { id: "lexus", name: "Lexus", slug: "lexus", cat: "automotive", desc: "Japanese luxury vehicle division of Toyota, known for exceptional quality, refinement, and innovative hybrid technology.", tagline: "The Relentless Pursuit of Perfection", logo: "🚗", year: 1989, founder: "Eiji Toyoda", bn: 9, z: "virgo", kw: ["luxury","reliability","hybrid","craftsmanship","Japanese"], lc: ["#000000","#FFFFFF"], ln: [9,2,4,6], energy: "The Perfectionist — pursues flawless quality and refined luxury" },
  { id: "mazda", name: "Mazda", slug: "mazda", cat: "automotive", desc: "Japanese automaker celebrated for sporty design, rotary engine heritage, and driver-focused engineering.", tagline: "Zoom-Zoom", logo: "🚗", year: 1920, founder: "Jujiro Matsuda", bn: 9, z: "sagittarius", kw: ["automotive","design","sports","innovation","Japanese"], lc: ["#101010","#FFFFFF"], ln: [9,3,5,7], energy: "The Enthusiast — drives with soul, passion, and joyful energy" },
  { id: "subaru", name: "Subaru", slug: "subaru", cat: "automotive", desc: "Japanese automaker known for symmetrical all-wheel drive, boxer engines, and outdoor lifestyle branding.", tagline: "Love. It's What Makes a Subaru, a Subaru", logo: "🚗", year: 1953, founder: "Kenji Kita, Chikuhei Nakajima", bn: 1, z: "sagittarius", kw: ["AWD","outdoor","reliability","safety","adventure"], lc: ["#013C6C","#FFFFFF"], ln: [1,4,6,9], energy: "The Companion — takes you on every adventure with unwavering reliability" },
  { id: "rivian", name: "Rivian", slug: "rivian", cat: "automotive", desc: "American electric vehicle manufacturer focused on adventure trucks and SUVs with sustainability at its core.", tagline: "Keep the World Adventurous Forever", logo: "🚙", year: 2009, founder: "RJ Scaringe", bn: 1, z: "aquarius", kw: ["EV","adventure","sustainability","truck","SUV"], lc: ["#6ADA6A","#FFFFFF"], ln: [1,3,5,9], energy: "The Adventurer — electrifies the great outdoors with sustainable adventure vehicles" },
  { id: "lucid", name: "Lucid Motors", slug: "lucid", cat: "automotive", desc: "American electric vehicle maker focused on luxury EVs with industry-leading range and efficiency.", tagline: "The Future of Luxury Electric", logo: "🚗", year: 2007, founder: "Bernard Tse, Sam Weng, Sheaupyng Lin", bn: 22, z: "aquarius", kw: ["EV","luxury","range","innovation","technology"], lc: ["#000000","#FFFFFF"], ln: [22,1,4,7], energy: "The Visionary — redefines luxury electric with unmatched efficiency" },
  { id: "byd", name: "BYD", slug: "byd", cat: "automotive", desc: "Chinese electric vehicle and battery manufacturer rapidly becoming the world's largest EV company.", tagline: "Build Your Dreams", logo: "🚗", year: 1995, founder: "Wang Chuanfu", bn: 4, z: "capricorn", kw: ["EV","battery","manufacturing","China","innovation"], lc: ["#C7153A","#FFFFFF"], ln: [4,2,6,8], energy: "The Builder — scales EV production with unprecedented vertical integration" },
  { id: "mini", name: "MINI", slug: "mini", cat: "automotive", desc: "British small car brand known for iconic retro design, go-kart handling, and premium character.", tagline: "The Iconic British Original", logo: "🚗", year: 1959, founder: "Alec Issigonis", bn: 9, z: "gemini", kw: ["British","compact","design","premium","iconic"], lc: ["#000000","#FFFFFF"], ln: [9,2,4,7], energy: "The Icon — proves that big character comes in small packages" },
  // === FASHION (more) ===
  { id: "balenciaga", name: "Balenciaga", slug: "balenciaga", cat: "fashion", desc: "Spanish-founded French luxury fashion house pushing boundaries with avant-garde design and streetwear influence.", tagline: "The House of Balenciaga", logo: "👗", year: 1919, founder: "Cristóbal Balenciaga", bn: 1, z: "aquarius", kw: ["luxury","avant-garde","streetwear","fashion","design"], lc: ["#000000","#FFFFFF"], ln: [1,4,6,9], energy: "The Radical — deconstructs fashion with bold, avant-garde vision" },
  { id: "saint-laurent", name: "Saint Laurent", slug: "saint-laurent", cat: "fashion", desc: "French luxury fashion house embodying rock-and-roll elegance and timeless Parisian sophistication.", tagline: "The Original Rock 'n' Roll Designer", logo: "👗", year: 1961, founder: "Yves Saint Laurent, Pierre Bergé", bn: 1, z: "libra", kw: ["luxury","fashion","rock","Parisian","elegance"], lc: ["#000000","#FFFFFF"], ln: [1,2,4,8], energy: "The Icon — merges rock rebellion with Parisian haute couture" },
  { id: "fendi", name: "Fendi", slug: "fendi", cat: "fashion", desc: "Italian luxury fashion house renowned for fur, leather goods, and the iconic double-F logo.", tagline: "The Roman Luxury House", logo: "👗", year: 1925, founder: "Adele Casagrande, Edoardo Fendi", bn: 2, z: "taurus", kw: ["luxury","leather","Italian","craftsmanship","fashion"], lc: ["#000000","#FFFFFF"], ln: [2,4,6,8], energy: "The Artisan — masters Roman craftsmanship with bold luxury" },
  { id: "valentino", name: "Valentino", slug: "valentino", cat: "fashion", desc: "Italian luxury fashion house celebrated for romantic elegance, exquisite craftsmanship, and iconic red gowns.", tagline: "Valentino: The Italian Dream", logo: "👗", year: 1960, founder: "Valentino Garavani, Giancarlo Giammetti", bn: 4, z: "libra", kw: ["luxury","romantic","Italian","haute-couture","elegance"], lc: ["#E30022","#FFFFFF"], ln: [4,2,6,9], energy: "The Romantic — weaves dreams with exquisite Italian craftsmanship" },
  { id: "coach", name: "Coach", slug: "coach", cat: "fashion", desc: "American fashion house known for accessible luxury leather goods, handbags, and lifestyle accessories.", tagline: "The Original American House of Leather", logo: "👛", year: 1941, founder: "Lillian and Miles Cahn", bn: 3, z: "taurus", kw: ["leather","handbags","accessories","American","luxury"], lc: ["#000000","#FFFFFF"], ln: [3,4,6,8], energy: "The Accessory — redefined accessible luxury with American craftsmanship" },
  { id: "uniqlo", name: "Uniqlo", slug: "uniqlo", cat: "fashion", desc: "Japanese casual wear brand known for innovative fabrics, minimalist design, and high-quality basics.", tagline: "LifeWear", logo: "👕", year: 1949, founder: "Tadashi Yanai", bn: 7, z: "virgo", kw: ["fashion","minimalist","Japanese","quality","essentials"], lc: ["#C41E24","#FFFFFF"], ln: [7,2,4,6], energy: "The Purist — perfects everyday essentials with Japanese simplicity" },
  { id: "supreme", name: "Supreme", slug: "supreme", cat: "fashion", desc: "American streetwear brand that became a cultural phenomenon through limited drops and hype-driven exclusivity.", tagline: "The Holy Grail of Streetwear", logo: "🔴", year: 1994, founder: "James Jebbia", bn: 7, z: "aquarius", kw: ["streetwear","hype","limited","skateboarding","collaboration"], lc: ["#FF0000","#000000"], ln: [7,1,4,9], energy: "The Hype — built an empire on scarcity and cultural cachet" },
  { id: "vans", name: "Vans", slug: "vans", cat: "fashion", desc: "American skateboarding shoe and apparel brand embodying off-the-wall creativity and youth culture.", tagline: "Off the Wall", logo: "👟", year: 1966, founder: "Paul Van Doren, Jim Van Doren, Gordon Lee", bn: 11, z: "aquarius", kw: ["skateboarding","shoes","youth","creative","action-sports"], lc: ["#000000","#FFFFFF"], ln: [11,2,4,6], energy: "The Rebel — empowers creative youth culture and action sports" },
  { id: "converse", name: "Converse", slug: "converse", cat: "fashion", desc: "American shoe company behind the iconic Chuck Taylor All Star, a timeless symbol of self-expression.", tagline: "The All Star, Since 1917", logo: "👟", year: 1908, founder: "Marquis Mills Converse", bn: 2, z: "pisces", kw: ["shoes","iconic","American","heritage","self-expression"], lc: ["#000000","#FFFFFF"], ln: [2,4,6,8], energy: "The Original — the canvas sneaker that became a global icon" },
  { id: "armani", name: "Armani", slug: "armani", cat: "fashion", desc: "Italian luxury fashion house defining understated elegance, impeccable tailoring, and red-carpet glamour.", tagline: "Timeless Elegance", logo: "👔", year: 1975, founder: "Giorgio Armani, Sergio Galeotti", bn: 2, z: "libra", kw: ["luxury","Italian","tailoring","elegance","fashion"], lc: ["#000000","#FFFFFF"], ln: [2,4,6,8], energy: "The Maestro — conducts Italian elegance with timeless sophistication" },
  { id: "alexander-mcqueen", name: "Alexander McQueen", slug: "alexander-mcqueen", cat: "fashion", desc: "British luxury fashion house known for dramatic, avant-garde designs and emotional runway shows.", tagline: "The Visionary", logo: "👗", year: 1992, founder: "Alexander McQueen", bn: 9, z: "scorpio", kw: ["avant-garde","British","dramatic","tailoring","fashion"], lc: ["#000000","#FFFFFF"], ln: [9,2,4,7], energy: "The Visionary — pushes fashion into the realm of art and emotion" },
  // === SPORTS (more) ===
  { id: "new-balance", name: "New Balance", slug: "new-balance", cat: "sports", desc: "American athletic footwear brand known for comfort, quality craftsmanship, and classic style.", tagline: "NB Connected", logo: "👟", year: 1906, founder: "William J. Riley", bn: 8, z: "taurus", kw: ["athletic","shoes","comfort","quality","American"], lc: ["#CF0034","#FFFFFF"], ln: [8,4,6,9], energy: "The Craftsperson — prioritizes comfort and quality over hype" },
  { id: "reebok", name: "Reebok", slug: "reebok", cat: "sports", desc: "British-founded athletic footwear brand with iconic legacy in aerobics, CrossFit, and training.", tagline: "The Sport of Fitness Has Arrived", logo: "👟", year: 1958, founder: "Joseph William Foster", bn: 2, z: "aries", kw: ["fitness","training","athletic","shoes","CrossFit"], lc: ["#E4002B","#FFFFFF"], ln: [2,4,6,8], energy: "The Fitness — revolutionized athletic training footwear for all" },
  { id: "asics", name: "ASICS", slug: "asics", cat: "sports", desc: "Japanese athletic footwear company focused on technical running shoes with scientific innovation.", tagline: "Sound Mind, Sound Body", logo: "👟", year: 1949, founder: "Kihachiro Onitsuka", bn: 6, z: "virgo", kw: ["running","shoes","technology","innovation","athletic"], lc: ["#000000","#FFFFFF"], ln: [6,2,4,8], energy: "The Runner — perfects running through scientific innovation" },
  // === ENTERTAINMENT (more) ===
  { id: "activision", name: "Activision Blizzard", slug: "activision", cat: "entertainment", desc: "Gaming powerhouse behind Call of Duty, World of Warcraft, and Candy Crush.", tagline: "Connecting the World Through Epic Entertainment", logo: "🎮", year: 1979, founder: "Jim Levy, Alan Miller, Bob Whitehead", bn: 3, z: "aries", kw: ["gaming","publishing","esports","entertainment","interactive"], lc: ["#000000","#000000"], ln: [3,1,5,9], energy: "The Titan — delivers epic interactive entertainment globally" },
  { id: "ea", name: "Electronic Arts", slug: "ea", cat: "entertainment", desc: "Major video game publisher known for sports franchises like FIFA, Madden, and iconic titles like The Sims.", tagline: "It's in the Game", logo: "🎮", year: 1982, founder: "Trip Hawkins", bn: 9, z: "sagittarius", kw: ["gaming","sports","entertainment","publishing","interactive"], lc: ["#DA282F","#000000"], ln: [9,3,5,7], energy: "The Athlete — brings competitive sports to life through interactive gaming" },
  { id: "unity", name: "Unity Technologies", slug: "unity", cat: "entertainment", desc: "Leading real-time 3D development platform powering games, simulations, and immersive experiences.", tagline: "Create with Unity", logo: "🎯", year: 2004, founder: "David Helgason, Joachim Ante, Nicholas Francis", bn: 8, z: "aquarius", kw: ["game-engine","3D","XR","development","real-time"], lc: ["#000000","#FFFFFF"], ln: [8,1,4,7], energy: "The Creator — democratizes 3D development for everyone" },
  // === FOOD & BEVERAGE (more) ===
  { id: "kellogg", name: "Kellogg's", slug: "kellogg", cat: "food-beverage", desc: "American multinational food company producing iconic breakfast cereals and convenience foods worldwide.", tagline: "The Original Breakfast Company", logo: "🥣", year: 1906, founder: "Will Keith Kellogg", bn: 33, z: "taurus", kw: ["cereal","breakfast","family","nutrition","iconic"], lc: ["#E2231A","#FFFFFF"], ln: [33,2,4,6], energy: "The Nourisher — feeds families every morning with iconic cereals" },
  { id: "mondelez", name: "Mondelez International", slug: "mondelez", cat: "food-beverage", desc: "Global snacking powerhouse behind Oreo, Cadbury, Ritz, Toblerone, and beloved confectionery brands worldwide.", tagline: "The Global Snacking Powerhouse", logo: "🍪", year: 2012, founder: "Irene Rosenfeld (spin-off from Kraft)", bn: 4, z: "taurus", kw: ["snacks","confectionery","global","chocolate","cookies"], lc: ["#005CAB","#FFFFFF"], ln: [4,2,6,8], energy: "The Snack Master — delivers joy through beloved treats worldwide" },
  { id: "danone", name: "Danone", slug: "danone", cat: "food-beverage", desc: "French multinational food company focused on dairy, plant-based products, bottled water, and specialized nutrition.", tagline: "One Planet. One Health", logo: "🥛", year: 1919, founder: "Isaac Carasso", bn: 8, z: "cancer", kw: ["dairy","yogurt","water","health","nutrition"], lc: ["#00529B","#FFFFFF"], ln: [8,2,4,6], energy: "The Health — nourishes global health through sustainable food" },
  { id: "hershey", name: "Hershey's", slug: "hershey", cat: "food-beverage", desc: "American chocolate manufacturer iconic for Hershey's Kisses, Reese's, and the sweet taste of Americana.", tagline: "The Sweetest Place on Earth", logo: "🍫", year: 1894, founder: "Milton S. Hershey", bn: 7, z: "cancer", kw: ["chocolate","candy","American","iconic","sweet"], lc: ["#000000","#FFFFFF"], ln: [7,2,4,6], energy: "The Sweetheart — brings joy through America's favorite chocolate" },
  { id: "mars", name: "Mars", slug: "mars", cat: "food-beverage", desc: "Family-owned global confectionery giant behind M&M's, Snickers, Mars bars, and pet food like Pedigree.", tagline: "The Mars Way", logo: "🍫", year: 1911, founder: "Franklin Clarence Mars", bn: 6, z: "taurus", kw: ["chocolate","candy","pet-care","family","global"], lc: ["#006B3E","#000000"], ln: [6,2,4,8], energy: "The Provider — satisfies cravings with beloved brands worldwide" },
  { id: "dunkin", name: "Dunkin'", slug: "dunkin", cat: "food-beverage", desc: "American coffee and donut chain serving millions daily with quick service, consistent quality, and affordable treats.", tagline: "America Runs on Dunkin'", logo: "☕", year: 1950, founder: "William Rosenberg", bn: 1, z: "gemini", kw: ["coffee","donuts","breakfast","fast-food","American"], lc: ["#E31937","#FF6E0D"], ln: [1,2,4,8], energy: "The Energizer — fuels America's mornings with coffee and donuts" },
  { id: "chipotle", name: "Chipotle", slug: "chipotle", cat: "food-beverage", desc: "American fast-casual chain revolutionizing Mexican food with fresh ingredients, customization, and sustainability.", tagline: "Food with Integrity", logo: "🌯", year: 1993, founder: "Steve Ells", bn: 7, z: "sagittarius", kw: ["fast-casual","Mexican","fresh","customization","sustainable"], lc: ["#8B4513","#FFFFFF"], ln: [7,3,5,9], energy: "The Fresh — redefined fast food with integrity and bold flavors" },
  { id: "guinness", name: "Guinness", slug: "guinness", cat: "food-beverage", desc: "Iconic Irish stout with a rich brewing heritage, distinctive dark flavor, and legendary advertising legacy.", tagline: "Good Things Come to Those Who Wait", logo: "🍺", year: 1759, founder: "Arthur Guinness", bn: 9, z: "taurus", kw: ["beer","stout","Irish","heritage","brewing"], lc: ["#000000","#FFFFFF"], ln: [9,4,6,8], energy: "The Icon — perfects the art of dark beer with 250+ years of heritage" },
  // === BEAUTY (more) ===
  { id: "lancome", name: "Lancôme", slug: "lancome", cat: "beauty", desc: "French luxury cosmetics house known for high-quality skincare, makeup, and signature fragrances.", tagline: "La vie est belle", logo: "💄", year: 1935, founder: "Armand Petitjean", bn: 9, z: "libra", kw: ["skincare","makeup","fragrance","luxury","French"], lc: ["#000000","#FFFFFF"], ln: [9,2,4,6], energy: "The Elegance — defines French beauty with timeless luxury" },
  { id: "shiseido", name: "Shiseido", slug: "shiseido", cat: "beauty", desc: "Japanese multinational personal care company blending Eastern philosophy with Western science in premium skincare.", tagline: "The Art of Beauty", logo: "💄", year: 1872, founder: "Arinobu Fukuhara", bn: 7, z: "virgo", kw: ["skincare","Japanese","premium","innovation","beauty"], lc: ["#000000","#FFFFFF"], ln: [7,2,4,8], energy: "The Artisan — perfects beauty through Japanese precision and artistry" },
  { id: "nivea", name: "Nivea", slug: "nivea", cat: "beauty", desc: "German personal care brand known for moisturizers, body care, and affordable skincare trusted by families worldwide.", tagline: "Caring for Skin. Caring for People.", logo: "🧴", year: 1911, founder: "Oscar Troplowitz", bn: 6, z: "cancer", kw: ["skincare","body-care","moisturizer","family","German"], lc: ["#003399","#FFFFFF"], ln: [6,2,4,8], energy: "The Caretaker — nurtures skin with gentle, trusted care" },
  { id: "dove", name: "Dove", slug: "dove", cat: "beauty", desc: "American personal care brand championing real beauty, self-esteem, and gentle moisturizing products.", tagline: "Real Beauty", logo: "🕊️", year: 1957, founder: "Unilever (Vincent Lamberti)", bn: 1, z: "cancer", kw: ["soap","body-wash","beauty","self-esteem","real"], lc: ["#004A96","#FFFFFF"], ln: [1,4,6,9], energy: "The Champion — redefines beauty with authenticity and confidence" },
  // === LUXURY (more) ===
  { id: "bulgari", name: "Bulgari", slug: "bulgari", cat: "luxury", desc: "Italian luxury jeweler and watchmaker celebrated for bold colored gemstones, Roman heritage, and exquisite craftsmanship.", tagline: "The Magnificent Roman Jeweler", logo: "💎", year: 1884, founder: "Sotirios Voulgaris", bn: 7, z: "leo", kw: ["jewelry","watches","Italian","luxury","craftsmanship"], lc: ["#000000","#FFFFFF"], ln: [7,1,4,8], energy: "The Magnificent — crafts Roman-inspired jewelry masterpieces" },
  { id: "patek-philippe", name: "Patek Philippe", slug: "patek-philippe", cat: "luxury", desc: "Geneva-based luxury watchmaker creating the world's finest timepieces with generations of watchmaking mastery.", tagline: "You Never Actually Own a Patek Philippe. You Merely Look After It for the Next Generation.", logo: "⌚", year: 1839, founder: "Antoni Patek, Adrien Philippe", bn: 9, z: "capricorn", kw: ["watches","Swiss","luxury","heritage","craftsmanship"], lc: ["#000000","#FFFFFF"], ln: [9,4,6,8], energy: "The Legacy — creates heirloom timepieces for generations" },
  { id: "montblanc", name: "Montblanc", slug: "montblanc", cat: "luxury", desc: "German luxury brand famed for fine writing instruments, watches, leather goods, and the iconic white star emblem.", tagline: "The Art of Writing", logo: "✒️", year: 1906, founder: "August Eberstein, Alfred Peschel, Claus Johannes Voss", bn: 4, z: "capricorn", kw: ["pens","watches","leather","luxury","writing"], lc: ["#000000","#FFFFFF"], ln: [4,2,6,8], energy: "The Scribe — elevates writing to an art of luxury" },
  { id: "swarovski", name: "Swarovski", slug: "swarovski", cat: "luxury", desc: "Austrian crystal manufacturer renowned for precision-cut crystals, jewelry, home décor, and sparkling elegance.", tagline: "Sparkle Your World", logo: "💎", year: 1895, founder: "Daniel Swarovski", bn: 2, z: "pisces", kw: ["crystal","jewelry","home-decor","Austrian","sparkle"], lc: ["#000000","#FFFFFF"], ln: [2,4,6,8], energy: "The Sparkler — illuminates the world with precision-cut crystal beauty" },
  // === FINANCE (more) ===
  { id: "morgan-stanley", name: "Morgan Stanley", slug: "morgan-stanley", cat: "finance", desc: "Global investment bank and wealth management firm advising institutions, governments, and individuals.", tagline: "The Wealth Manager", logo: "🏛️", year: 1935, founder: "Henry Sturgis Morgan, Harold Stanley", bn: 2, z: "capricorn", kw: ["investment","wealth","banking","management","global"], lc: ["#000000","#FFFFFF"], ln: [2,4,6,8], energy: "The Steward — manages global wealth with institutional authority" },
  { id: "citibank", name: "Citibank", slug: "citibank", cat: "finance", desc: "Global banking and financial services arm of Citigroup, serving retail and corporate clients across 100+ countries.", tagline: "The World's Citi", logo: "🏛️", year: 1812, founder: "Samuel Osgood", bn: 33, z: "capricorn", kw: ["banking","global","retail","corporate","finance"], lc: ["#003DA6","#FFFFFF"], ln: [33,2,4,6], energy: "The Global — serves the world's banking needs across borders" },
  { id: "blackrock", name: "BlackRock", slug: "blackrock", cat: "finance", desc: "World's largest asset manager with over $10 trillion in assets under management, shaping global finance.", tagline: "Investing for a New World", logo: "🏛️", year: 1988, founder: "Larry Fink, Rob Kapito, Susan Wagner, Ben Golub, Barbara Novick, Ralph Schlosstein", bn: 4, z: "capricorn", kw: ["asset-management","investing","global","finance","iShares"], lc: ["#000000","#FFFFFF"], ln: [4,2,6,8], energy: "The Giant — manages the world's largest pool of investment capital" },
  { id: "vanguard", name: "Vanguard", slug: "vanguard", cat: "finance", desc: "Investment management company revolutionizing passive investing with low-cost index funds and client-owned structure.", tagline: "The Investor's Company", logo: "🏛️", year: 1975, founder: "John C. Bogle", bn: 7, z: "virgo", kw: ["investing","index-funds","low-cost","retirement","passive"], lc: ["#00A3E0","#FFFFFF"], ln: [7,2,4,8], energy: "The Democratizer — made low-cost investing accessible for everyone" },
  { id: "fidelity", name: "Fidelity Investments", slug: "fidelity", cat: "finance", desc: "Global financial services firm offering brokerage, retirement, wealth management, and investment guidance.", tagline: "The Power to Help You Succeed", logo: "🏛️", year: 1946, founder: "Edward C. Johnson II", bn: 7, z: "taurus", kw: ["brokerage","retirement","investing","mutual-funds","wealth"], lc: ["#008542","#FFFFFF"], ln: [7,4,6,9], energy: "The Guide — helps investors build and preserve generational wealth" },
  // === TRAVEL & HOSPITALITY (more) ===
  { id: "hyatt", name: "Hyatt", slug: "hyatt", cat: "travel-hospitality", desc: "Global hospitality company operating luxury and upscale hotels worldwide with a focus on care and wellness.", tagline: "World of Care", logo: "🏨", year: 1957, founder: "Jay Pritzker", bn: 2, z: "cancer", kw: ["hotels","hospitality","luxury","wellness","travel"], lc: ["#006DAA","#FFFFFF"], ln: [2,4,6,8], energy: "The Caretaker — creates welcoming spaces with genuine hospitality" },
  { id: "singapore-airlines", name: "Singapore Airlines", slug: "singapore-airlines", cat: "travel-hospitality", desc: "Award-winning airline renowned for exceptional cabin service, Singapore Girl hospitality, and premium flying experience.", tagline: "A Great Way to Fly", logo: "✈️", year: 1947, founder: "Malaysia-Singapore Airlines predecessor", bn: 2, z: "libra", kw: ["aviation","luxury","service","premium","Asian"], lc: ["#F9A800","#FFFFFF"], ln: [2,4,6,9], energy: "The Concierge — sets the global standard for in-flight service" },
  { id: "qatar-airways", name: "Qatar Airways", slug: "qatar-airways", cat: "travel-hospitality", desc: "Qatari airline known for ultra-luxury Qsuite business class, world-class lounges, and global connectivity.", tagline: "Going Places Together", logo: "✈️", year: 1993, founder: "Government of Qatar", bn: 9, z: "leo", kw: ["aviation","luxury","Qsuite","middle-east","premium"], lc: ["#A60A2F","#FFFFFF"], ln: [9,1,5,8], energy: "The Majestic — redefines air travel luxury with visionary innovation" },
  { id: "accor", name: "Accor", slug: "accor", cat: "travel-hospitality", desc: "French hospitality group operating over 5,000 hotels worldwide across luxury, premium, and economy brands.", tagline: "The Heart of Hospitality", logo: "🏨", year: 1967, founder: "Paul Dubrule, Gérard Pélisson", bn: 22, z: "cancer", kw: ["hotels","hospitality","French","global","luxury"], lc: ["#000000","#FFFFFF"], ln: [22,4,6,9], energy: "The Heart — welcomes travelers across 5,000 hotels worldwide" },
  // === RETAIL (more) ===
  { id: "home-depot", name: "The Home Depot", slug: "home-depot", cat: "retail", desc: "American home improvement giant offering tools, building materials, and DIY solutions for homeowners and professionals.", tagline: "More Saving. More Doing.", logo: "🔨", year: 1978, founder: "Bernard Marcus, Arthur Blank, Ron Brill, Pat Farrah", bn: 2, z: "taurus", kw: ["home-improvement","tools","DIY","hardware","retail"], lc: ["#F96302","#FFFFFF"], ln: [2,4,6,8], energy: "The Builder — empowers DIYers and pros to build their dreams" },
  { id: "best-buy", name: "Best Buy", slug: "best-buy", cat: "retail", desc: "American electronics retailer providing technology products, services, and Geek Squad support.", tagline: "Let's Talk About What's Possible", logo: "📱", year: 1966, founder: "Richard Schulze", bn: 22, z: "gemini", kw: ["electronics","retail","technology","gadgets","service"], lc: ["#0046BE","#FFFFFF"], ln: [22,2,4,6], energy: "The Advisor — helps customers navigate the world of technology" },
  { id: "nordstrom", name: "Nordstrom", slug: "nordstrom", cat: "retail", desc: "American luxury department store known for exceptional customer service, designer fashion, and personalized shopping.", tagline: "The Nordstrom Difference", logo: "👗", year: 1901, founder: "John W. Nordstrom, Carl F. Wallin", bn: 1, z: "libra", kw: ["retail","fashion","luxury","service","department-store"], lc: ["#000000","#FFFFFF"], ln: [1,4,6,8], energy: "The Concierge — sets the standard for premium retail service" },
  { id: "aldi", name: "ALDI", slug: "aldi", cat: "retail", desc: "German discount supermarket chain known for high-quality private-label products at remarkably low prices.", tagline: "The Smart Way to Shop", logo: "🛒", year: 1946, founder: "Karl Albrecht, Theo Albrecht", bn: 8, z: "taurus", kw: ["grocery","discount","private-label","efficiency","value"], lc: ["#0050B3","#FFFFFF"], ln: [8,2,4,6], energy: "The Efficient — revolutionized grocery shopping with streamlined simplicity" },
  { id: "tesco", name: "Tesco", slug: "tesco", cat: "retail", desc: "British multinational grocery and general merchandise retailer, the largest in the UK with global operations.", tagline: "Every Little Helps", logo: "🛒", year: 1919, founder: "Jack Cohen", bn: 8, z: "taurus", kw: ["grocery","retail","UK","supermarket","value"], lc: ["#EE1C2E","#FFFFFF"], ln: [8,4,6,9], energy: "The Helper — serves communities with everyday value and convenience" },
  // === HEALTH & FITNESS (more) ===
  { id: "lululemon", name: "Lululemon", slug: "lululemon", cat: "health-fitness", desc: "Canadian athletic apparel brand pioneering technical yoga wear and community-driven fitness lifestyle.", tagline: "This Is Yoga", logo: "🧘", year: 1998, founder: "Chip Wilson", bn: 8, z: "sagittarius", kw: ["yoga","athleisure","community","fitness","wellness"], lc: ["#D31334","#FFFFFF"], ln: [8,3,5,9], energy: "The Yogi — inspires mindful movement and community wellness" },
  { id: "peloton", name: "Peloton", slug: "peloton", cat: "health-fitness", desc: "Connected fitness company with cutting-edge stationary bikes, treadmills, and on-demand studio classes.", tagline: "The Peloton Experience", logo: "🚴", year: 2012, founder: "John Foley, Tom Cortese, Graham Stanton, Hisao Kushi, Yony Feng", bn: 7, z: "aries", kw: ["fitness","connected","cycling","class","home"], lc: ["#000000","#FFFFFF"], ln: [7,1,4,9], energy: "The Motivator — brings studio energy into every home workout" },
  { id: "fitbit", name: "Fitbit", slug: "fitbit", cat: "health-fitness", desc: "Wearable fitness tracker pioneer helping millions achieve health goals through activity tracking and insights.", tagline: "Find Your Fit", logo: "⌚", year: 2007, founder: "James Park, Eric Friedman", bn: 3, z: "aries", kw: ["wearable","fitness","tracker","health","steps"], lc: ["#00B0B9","#FFFFFF"], ln: [3,1,5,8], energy: "The Tracker — empowers healthier lives through data-driven activity insights" },
  { id: "garmin", name: "Garmin", slug: "garmin", cat: "health-fitness", desc: "GPS technology company specializing in outdoor, fitness, aviation, and marine navigation and wearables.", tagline: "Be the Leader", logo: "📡", year: 1989, founder: "Gary Burrell, Min Kao", bn: 8, z: "sagittarius", kw: ["GPS","fitness","wearables","outdoor","navigation"], lc: ["#000000","#FFFFFF"], ln: [8,3,5,7], energy: "The Navigator — guides adventurers with precision GPS technology" },
  { id: "herbalife", name: "Herbalife", slug: "herbalife", cat: "health-fitness", desc: "Global nutrition company providing weight management, sports nutrition, and personal care products.", tagline: "The Better You", logo: "🌿", year: 1980, founder: "Mark Hughes", bn: 3, z: "pisces", kw: ["nutrition","weight-management","wellness","supplements","fitness"], lc: ["#006837","#FFFFFF"], ln: [3,1,4,7], energy: "The Nourisher — helps people achieve their health and wellness goals" },
];

export const BRANDS: Brand[] = RAW.map(transformBrand);

export const BRANDS_BY_CATEGORY: Record<BrandCategory, Brand[]> = (() => {
  const map: Record<string, Brand[]> = {};
  for (const b of BRANDS) {
    if (!map[b.category]) map[b.category] = [];
    map[b.category].push(b);
  }
  return map as Record<BrandCategory, Brand[]>;
})();

export const BRAND_CATEGORIES: BrandCategory[] = [
  "technology","automotive","fashion","food-beverage",
  "beauty","luxury","entertainment","sports",
  "finance","travel-hospitality","retail","health-fitness",
];

export function findBrand(slug: string): Brand | undefined {
  return RAW.map(transformBrand).find((b) => b.slug === slug);
}

export function searchBrands(query: string): Brand[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return RAW
    .map(transformBrand)
    .filter(
      (b) =>
        b.name.toLowerCase().includes(q) ||
        b.description.toLowerCase().includes(q) ||
        b.keywords.some((k) => k.toLowerCase().includes(q)) ||
        b.founder.toLowerCase().includes(q) ||
        b.category.toLowerCase().includes(q)
    )
    .slice(0, 50);
}
