import type { PlanetName, ZodiacSign } from '@/types/cosmic';

export interface PlanetTransitData {
  planet: PlanetName;
  title: string;
  transitThroughSign: Record<ZodiacSign, string>;
  retrogradeNote: string;
}

export const TRANSIT_INTERPRETATIONS: PlanetTransitData[] = [
  {
    planet: 'sun',
    title: 'The Illuminator',
    retrogradeNote: 'The Sun never appears retrograde from Earth.',
    transitThroughSign: {
      aries: 'Identity ignites — bold new beginnings and courageous self-expression dominate the season.',
      taurus: 'Grounding energy — focus shifts to security, comfort, and building lasting value.',
      gemini: 'Communication flourishes — curiosity, networking, and mental agility are highlighted.',
      cancer: 'Emotional depth — themes of home, family, and nurturing take center stage.',
      leo: 'Radiance peaks — creativity, confidence, and joyful self-expression are amplified.',
      virgo: 'Refinement — attention to detail, health, and service brings meaningful improvement.',
      libra: 'Balance seeks beauty — relationships, aesthetics, and fairness are illuminated.',
      scorpio: 'Intensity deepens — transformation, power dynamics, and hidden truths surface.',
      sagittarius: 'Expansion calls — adventure, philosophy, and optimism broaden horizons.',
      capricorn: 'Ambition focuses — career, responsibility, and long-term structures demand attention.',
      aquarius: 'Innovation sparks — originality, community, and humanitarian vision come alive.',
      pisces: 'Spirituality deepens — intuition, compassion, and surrender to the divine flow.',
    },
  },
  {
    planet: 'moon',
    title: 'The Emotional Tide',
    retrogradeNote: 'The Moon does not go retrograde.',
    transitThroughSign: {
      aries: 'Emotions run hot and fast — impulsive feelings demand immediate expression and action.',
      taurus: 'Emotional stability is sought — comfort food, cozy spaces, and sensual pleasures soothe.',
      gemini: 'Feelings fluctuate rapidly — the mind processes emotions through words and social connection.',
      cancer: 'Deep emotional nurturing — home and family feelings are amplified and tender.',
      leo: 'Emotions seek dramatic expression — creativity and romance feel theatrically intense.',
      virgo: 'Emotional perfectionism — worry and service merge as care is expressed through doing.',
      libra: 'Emotional harmony is paramount — peace in relationships and aesthetic beauty soothe the soul.',
      scorpio: 'Emotional depths are plumbed — intense feelings, secrets, and transformative power surge.',
      sagittarius: 'Emotions seek freedom — optimism, adventure, and philosophical comfort expand the heart.',
      capricorn: 'Emotional reserve strengthens — feelings are channeled into achievement and responsibility.',
      aquarius: 'Emotions detach slightly — intellectual processing and community connection provide solace.',
      pisces: 'Emotional boundaries dissolve — empathy, dreams, and spiritual connection overwhelm the senses.',
    },
  },
  {
    planet: 'mercury',
    title: 'The Messenger',
    retrogradeNote: 'Mercury retrograde (3 times/year, ~3 weeks each): Miscommunications, technology glitches, and revisiting the past. Review, revise, and reflect rather than initiate.',
    transitThroughSign: {
      aries: 'Thinking turns sharp and decisive — communication is direct, fast, and assertive.',
      taurus: 'Thoughts slow to savor — practical thinking, financial planning, and sensual awareness deepen.',
      gemini: 'Mental agility peaks — multitasking, socializing, and intellectual curiosity flourish.',
      cancer: 'Thoughts turn inward — emotional intelligence, memory, and intuitive understanding deepen.',
      leo: 'Communication becomes dramatic — creative ideas demand bold, confident expression.',
      virgo: 'Analytical precision — details matter, editing improves, and practical problem-solving excels.',
      libra: 'Diplomatic thinking — weighing options, seeking fairness, and charming communication prevail.',
      scorpio: 'Mental intensity — research deepens, secrets are uncovered, and penetrating insight emerges.',
      sagittarius: 'Big-picture thinking — philosophy, learning, and expansive communication take the lead.',
      capricorn: 'Strategic planning — thoughts focus on career, structure, and long-term goals.',
      aquarius: 'Innovative thinking — original ideas, technology, and group collaboration spark brilliance.',
      pisces: 'Intuitive processing — imagination, dreams, and spiritual communication transcend logic.',
    },
  },
  {
    planet: 'venus',
    title: 'The Enchantress',
    retrogradeNote: 'Venus retrograde (every 18 months, ~6 weeks): Love and values are reassessed. Past lovers may return. Financial shifts and relationship re-evaluations occur.',
    transitThroughSign: {
      aries: 'Love pursues boldly — romantic initiative, passionate beginnings, and confident charm.',
      taurus: 'Sensuality peaks — luxury, comfort, and lasting love are savored and appreciated.',
      gemini: 'Love flirts — witty charm, intellectual connection, and social romance excite.',
      cancer: 'Love nurtures — emotional intimacy, home comforts, and tender affection deepen.',
      leo: 'Love performs — grand romantic gestures, creative passion, and dramatic allure shine.',
      virgo: 'Love serves — practical care, thoughtful details, and devoted attention express affection.',
      libra: 'Love harmonizes — beauty, partnership, and romantic idealism are perfectly aligned.',
      scorpio: 'Love transforms — intense passion, magnetic attraction, and soul-deep intimacy consume.',
      sagittarius: 'Love adventures — freedom in relationships, philosophical connection, and optimistic romance.',
      capricorn: 'Love commits — serious relationships, long-term partnerships, and practical devotion solidify.',
      aquarius: 'Love liberates — unconventional romance, friendship-based love, and humanitarian warmth.',
      pisces: 'Love dissolves boundaries — romantic fantasy, spiritual connection, and unconditional compassion.',
    },
  },
  {
    planet: 'mars',
    title: 'The Warrior',
    retrogradeNote: 'Mars retrograde (every 2 years, ~11 weeks): Aggression turns inward. Energy may feel blocked. Use this time for strategy rather than direct action.',
    transitThroughSign: {
      aries: 'Raw power peaks — physical energy, competitive drive, and assertive action are at maximum.',
      taurus: 'Steady determination — persistent effort, sensual drive, and patient building of force.',
      gemini: 'Mental energy surges — arguments, debates, multitasking, and scattered physical activity.',
      cancer: 'Defensive strength — protective instincts, emotional battles, and domestic conflicts.',
      leo: 'Dramatic action — creative fire, passionate pursuits, and bold self-expression burn bright.',
      virgo: 'Productive energy — focused work, health improvement, and analytical effort channel power.',
      libra: 'Diplomatic force — fighting for fairness, relationship conflicts, and aesthetic battles.',
      scorpio: 'Intense power — strategic action, hidden aggression, and transformative force mobilize.',
      sagittarius: 'Adventurous energy — physical exploration, philosophical battles, and optimistic drive.',
      capricorn: 'Ambitious power — career battles, disciplined effort, and authority assertions strengthen.',
      aquarius: 'Revolutionary energy — fights for freedom, group activism, and innovative action.',
      pisces: 'Passive resistance — spiritual warfare, indirect action, and surrendered strength.',
    },
  },
  {
    planet: 'jupiter',
    title: 'The Benefactor',
    retrogradeNote: 'Jupiter retrograde (~4 months/year): External expansion turns inward. Spiritual growth and philosophical reflection deepen. Luck may come through unexpected internal insights.',
    transitThroughSign: {
      aries: 'Expansive beginnings — new ventures prosper, confidence grows, and opportunities for leadership arise.',
      taurus: 'Material abundance — financial growth, comfort expansion, and sensual pleasures increase.',
      gemini: 'Knowledge expands — learning opportunities, social connections, and communication gifts multiply.',
      cancer: 'Emotional growth — family blessings, home expansion, and nurturing opportunities abound.',
      leo: 'Creative abundance — artistic growth, romantic opportunities, and joyful expression flourish.',
      virgo: 'Health expansion — wellness improvements, service opportunities, and practical growth.',
      libra: 'Relationship blessings — partnership growth, social harmony, and aesthetic expansion.',
      scorpio: 'Transformational growth — deep healing, shared resource blessings, and intimate expansion.',
      sagittarius: 'Maximum expansion — philosophical growth, travel blessings, and optimistic breakthroughs.',
      capricorn: 'Career advancement — professional growth, authority expansion, and structured success.',
      aquarius: 'Innovative growth — community blessings, technological advancement, and humanitarian expansion.',
      pisces: 'Spiritual expansion — intuition deepens, compassion grows, and transcendent experiences multiply.',
    },
  },
  {
    planet: 'saturn',
    title: 'The Taskmaster',
    retrogradeNote: 'Saturn retrograde (~4.5 months/year): External structures are challenged. Internal restructuring begins. Review commitments, responsibilities, and areas of restriction.',
    transitThroughSign: {
      aries: 'Discipline tests identity — patience with self, mastering independence through structured action.',
      taurus: 'Security is tested — financial lessons, patience with material growth, and value restructuring.',
      gemini: 'Communication is disciplined — learning patience in expression, honest dialogue, and mental focus.',
      cancer: 'Emotional maturation — family responsibilities, home restructuring, and emotional boundaries.',
      leo: 'Creative discipline — humility in self-expression, responsibility in romance, and patient artistry.',
      virgo: 'Perfectionism matures — service without burnout, health restructuring, and practical wisdom.',
      libra: 'Relationship lessons — commitment maturity, partnership restructuring, and balanced responsibility.',
      scorpio: 'Transformation through discipline — facing fears, shared resource lessons, and intimate maturity.',
      sagittarius: 'Philosophical maturity — tempering optimism with realism, travel discipline, and belief restructuring.',
      capricorn: 'Amplified authority — career restructuring, leadership lessons, and ambition tempered by wisdom.',
      aquarius: 'Structure meets innovation — community responsibility, friendship maturity, and visionary discipline.',
      pisces: 'Spiritual discipline — grounding intuition, boundary setting, and transcendent responsibility.',
    },
  },
  {
    planet: 'uranus',
    title: 'The Awakener',
    retrogradeNote: 'Uranus retrograde (~5 months/year): External revolution turns to internal awakening. Personal liberation unfolds through inner change rather than outer disruption.',
    transitThroughSign: {
      aries: 'Revolutionary identity — sudden independence, technological breakthroughs in self-expression.',
      taurus: 'Financial upheaval — value system transformation, unexpected wealth shifts, and liberation from materialism.',
      gemini: 'Communication revolution — technology transforms how we connect, information becomes liberated.',
      cancer: 'Domestic revolution — home life disruption, family paradigm shifts, and emotional liberation.',
      leo: 'Creative revolution — artistic breakthroughs, unconventional romance, and freedom in self-expression.',
      virgo: 'Health revolution — wellness paradigm shifts, work transformation, and service innovation.',
      libra: 'Relationship revolution — partnership paradigm shifts, unconventional love, and balance disruption.',
      scorpio: 'Power revolution — financial upheaval, intimacy transformation, and depth liberation.',
      sagittarius: 'Philosophical revolution — belief paradigm shifts, travel disruption, and wisdom liberation.',
      capricorn: 'Authority revolution — career upheaval, structural transformation, and power liberation.',
      aquarius: 'Maximum revolution — humanitarian breakthroughs, social transformation, and freedom explosion.',
      pisces: 'Spiritual revolution — consciousness paradigm shifts, faith transformation, and transcendence liberation.',
    },
  },
  {
    planet: 'neptune',
    title: 'The Mystic',
    retrogradeNote: 'Neptune retrograde (~5 months/year): Illusions are stripped away. Spiritual truth emerges through inner clarity rather than external fantasy.',
    transitThroughSign: {
      aries: 'Spiritual identity confusion — the self dissolves into something greater, faith becomes personal.',
      taurus: 'Material dreams tested — values become spiritualized, materialism loses its grip.',
      gemini: 'Mental fog and inspiration — imagination transcends logic, spiritual communication emerges.',
      cancer: 'Emotional dissolution — empathy overflows, spiritual nurturing transforms home life.',
      leo: 'Creative transcendence — art becomes spiritual practice, romance becomes devotion.',
      virgo: 'Service becomes sacred — healing work transforms, practical spirituality emerges.',
      libra: 'Relationship idealism — spiritual partnership, romantic transcendence, and beauty as divinity.',
      scorpio: 'Psychic deepening — intuitive power surges, spiritual transformation through darkness.',
      sagittarius: 'Philosophical transcendence — faith expands beyond dogma, spiritual adventure calls.',
      capricorn: 'Spiritual structure — dreams meet reality, faith becomes practical, mysticism matures.',
      aquarius: 'Collective awakening — humanitarian vision spiritualizes, technology becomes transcendent.',
      pisces: 'Maximum mysticism — consciousness dissolves boundaries, spiritual gifts peak, compassion overflows.',
    },
  },
  {
    planet: 'pluto',
    title: 'The Transformer',
    retrogradeNote: 'Pluto retrograde (~5 months/year): External transformation turns internal. Deep psychological work, shadow integration, and inner rebirth.',
    transitThroughSign: {
      aries: 'Identity transformation — the self is destroyed and reborn through fierce individual will.',
      taurus: 'Values destruction — material attachments transform, self-worth is rebuilt from the ground up.',
      gemini: 'Mental transformation — old thought patterns die, communication becomes powerfully authentic.',
      cancer: 'Emotional rebirth — family patterns dissolve, deep emotional healing transforms roots.',
      leo: 'Power transformation — ego death and rebirth, creative power is spiritualized.',
      virgo: 'Health rebirth — the body transforms, service becomes empowerment, perfectionism heals.',
      libra: 'Relationship alchemy — partnerships transform through depth, balance is rebuilt from truth.',
      scorpio: 'Maximum power — complete transformation, death and rebirth in the most intimate spaces.',
      sagittarius: 'Belief transformation — philosophy is demolished and rebuilt, wisdom through destruction.',
      capricorn: 'Authority rebirth — power structures transform, career is rebuilt from authentic foundation.',
      aquarius: 'Collective transformation — societal structures revolutionize, freedom is reborn through upheaval.',
      pisces: 'Spiritual death and rebirth — consciousness transforms completely, transcendence through surrender.',
    },
  },
];

export function getPlanetTransitData(planet: PlanetName): PlanetTransitData | undefined {
  return TRANSIT_INTERPRETATIONS.find((p) => p.planet === planet);
}

export function getTransitSignInterpretation(planet: PlanetName, sign: ZodiacSign): string {
  return getPlanetTransitData(planet)?.transitThroughSign[sign] ?? `Transiting ${planet} in ${sign} brings shifting energies.`;
}

export const PLANET_WEIGHTS: Record<PlanetName, number> = {
  sun: 1.0,
  moon: 0.9,
  mercury: 0.5,
  venus: 0.6,
  mars: 0.6,
  jupiter: 0.8,
  saturn: 0.9,
  uranus: 0.8,
  neptune: 0.7,
  pluto: 0.9,
};
